### ISSUE TITLE
I don't want use Cocoapods and Carthage,and where i can download DFULibrary.framework

### ISSUE THREAD

**Issue by coderCooper** [nordicsemi/IOS-DFU-Library#103]
I don't want use Cocoapods and Carthage,and where i can download DFULibrary.framework.

At https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/documentation.md#integration,
I found can use DFULibrary.framework,but i can't find the url which can download this file.
Tks.

**Comment by mostafaberg** [comment]
Hi @darling-shadow We do not supply binaries like framework files and such, but you may checkout this repository and build the framework target, this will give you the framework files needed that you may copy directly into your project.

**Comment by coderCooper** [comment]
Hi, @mostafaberg thanks for your advice,I used Carthage at last.
