### ISSUE TITLE
the lower lib which use swift2.3 depends on the zip package is swift3

### ISSUE THREAD

**Issue by iCalabash** [nordicsemi/IOS-DFU-Library#104]
Hello, I am using the swift2.3 version of the library, but when I perform pod install, due to depend on the library version of the problem, pod will install the latest zip package, which is the latest swift3 version, hoping to Update a newer version 2.3, and add the correct version management to the dependent zip.
Waiting online！...

**Comment by mostafaberg** [comment]
Swift 2.3 is deprecated and we do not recommend using swift 2.3 anymore. the best solution is to upgrade your project to use Swift 3. our library and the Zip dependency have many updates and improvements since the Swift 2.3 versions too so you will be having a better experience as a developer
