### ISSUE TITLE
OC call Swift

### ISSUE THREAD

**Issue by wokenshin** [nordicsemi/IOS-DFU-Library#105]
Hi god, sorry, can you write an Objective-C call to Swift's demo. Because there are many needs to be completed in the OC

**Comment by wokenshin** [comment]
I found that the importation of the framework of the first document is OC, so it should be used directly. Haha sorry

**Comment by mostafaberg** [comment]
No worries, glad to hear your project worked, for future reference you may follow the objective-C installation steps found [here](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/README_OBJC.md)
