### ISSUE TITLE
Is this compatible with SDk v13.0.0?

### ISSUE THREAD

**Issue by pruthvikar** [nordicsemi/IOS-DFU-Library#108]
I was wondering if the library needs to be changed to work with SDK v13.0.0.

I am aware that the buttonless DFU service and characteristic have changed UUIDs, and that there are extended error codes. I was wondering if that means this library at v3.1.0 is still compatible?

**Comment by mostafaberg** [comment]
I'm not sure i'm following the question, do  you mean to ask if v3.1.0 is compatible with SDK v13 ? or if earlier versions are compatitble with SDK 13 ?

**Comment by pruthvikar** [comment]
I meant to ask, is version v3.1.0 compatible with SDK v13?

**Comment by mostafaberg** [comment]
Yes it is, you can see that in the release here :)
https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/releases/tag/3.1.0

**Comment by pruthvikar** [comment]
Oh, perfect, thanks!

**Comment by mostafaberg** [comment]
No worries :) lest us know if you have any more questions!
