### ISSUE TITLE
Want to send the start command to the BLE device to get the readings from the device

### ISSUE THREAD

**Issue by lovekeshsaxena** [nordicsemi/IOS-DFU-Library#112]
I have FORA BP device and i am using your library to get the readings from the device. Need to start the device from the application. IS there any way to achieve that?

**Comment by mostafaberg** [comment]
Hi!, can you clarify a bit more what you mean by "start the device from applicatoin" ?
Also, what do you mean "using this library to get readings form the device" ? this library is only for flashing firmwares on supported peripherals, it's not used for reading any other types of data on your BLE peripheral
