### ISSUE TITLE
DFU does not work for nRF52

### ISSUE THREAD

**Issue by jrossano** [nordicsemi/IOS-DFU-Library#116]
There is no way to change the MBR size from the default 4096 (0x1000) to 12288 (0x3000) , which is required to update the nRF52.

**Comment by philips77** [comment]
Hi, 
You are correct. This is now hardcoded: https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Utilities/HexToBinConverter/IntelHex2BinConverter.m#L158
Please use the ZIP format instead. To create the ZIP use [nrfutil](https://github.com/NordicSemiconductor/pc-nrfutil). It automatically converts hex to bin and then conversion is no longer required on the phone. The file is also smaller and contains dat file inside.
