### ISSUE TITLE
Change DFU Service UUID

### ISSUE THREAD

**Issue by rahul-sciter** [nordicsemi/IOS-DFU-Library#121]
I have multiple bluetooth devices which have different DFU Service UUID. How can i change DFU Service UUID runtime using iOS DFU Library.

**Comment by philips77** [comment]
Hi, currently it is not possible in iOS DFU library. May I ask why did you decide to have multiple UUIDs for DFU?

**Comment by rahul-sciter** [comment]
We have developed multiple hardware each have different UUID for DFU Service. So I have developed one application which support all bluetooth devices. So I want to integrate firmware upgrade for all bluetooth devices. So if user select device for firmware upgrade based on that i need to scan DFU Device.

**Comment by rahul-sciter** [comment]
In android library you have provided one flag EXTRA_CUSTOM_UUIDS_FOR_LEGACY_DFU on that bases your android library works for multiple DFU Service UUID.

**Comment by rahul-sciter** [comment]
In Android library in this class **UuidHelper.java** there is one function **UuidHelper.assignCustomUuids(intent);** by calling it we can assign UUID from our application.
Is this possible in iOS Library?

**Comment by rahul-sciter** [comment]
Can anyone answer me on this?

**Comment by mostafaberg** [comment]
@rahul-sciter Sorry for the late response, right now it's not officially supported on the iOS library, but if you want to [overwrite it yourself](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/LegacyDFU/Services/LegacyDFUService.swift#L26) that should be ok, if you want to modify it at runtime it's just a matter of adding your own initializer that takes in a custom `UUID` for the service, it's hard to tell the exact solution without seeing your use case and code, but that should be the way to do it

**Comment by mostafaberg** [comment]
@rahul-sciter Any updates on the issue ? have you got things working or do you require help ?
