### ISSUE TITLE
Dont't find application service

### ISSUE THREAD

**Issue by DonYau** [nordicsemi/IOS-DFU-Library#123]
After OTA,I can find update service,but not discover application service.I think the bootloader dont;t change appliction

**Comment by mostafaberg** [comment]
Please provide more information and logs so we can help you :)

**Comment by mostafaberg** [comment]
Issue is getting stale, if we hear no updates from you within the week we will assume the issue is resolved and will close this issue, you are more than welcome to reopen a new one if the issue still persists and we have closed this one :)
