### ISSUE TITLE
About BLE pairing on the IOS platform...

### ISSUE THREAD

**Issue by developerXiong** [nordicsemi/IOS-DFU-Library#127]
I have a question to ask you about Bluetooth pairing.I want to use the code to enter the pairing password and cancel the system pop-up window when it is paired. if you have answer, please tell me, thank you very much!!!!!!

**Comment by mostafaberg** [comment]
Hi @developerXiong Pairing on iOS is handled by the operating system and is not overridable by the developers, so you will have to use the system popup unfortunately

**Comment by developerXiong** [comment]
if I add the method  - (void)peripheral:(CBPeripheral *)peripheral didWriteValueForCharacteristic:(CBCharacteristic *)characteristic error:(nullable NSError *)error,,, and write here nothing, the system pop-up will be hide...

**Comment by mostafaberg** [comment]
Must be something else that's crashing, but anyways no matter what you attempt you can't override that iOS has to handle the Pairing and not your app

**Comment by developerXiong** [comment]
OK! thank you
