### ISSUE TITLE
data instead of just url for init

### ISSUE THREAD

**Issue by tcurdt** [nordicsemi/IOS-DFU-Library#130]
The `DFUFirmware` init only allows `URL`s to be passed in for the zip, hex and dat files.
This is really inconvenient and not the best interface for the API. It would be great if one could pass in `Data` objects instead.

**Comment by tcurdt** [comment]
Same goes for `DFUStreamBin`, `DFUStreamHex` and `DFUStreamZip`

**Comment by philips77** [comment]
Good idea. I'll look into it soon.

**Comment by philips77** [comment]
@tcurdt Could you check the PR?

**Comment by tcurdt** [comment]
I agree with some of the comments that @mostafaberg made - but they are no blockers. So...
Looking good to me. Thanks!
