### ISSUE TITLE
DfuTarg

### ISSUE THREAD

**Issue by tcurdt** [nordicsemi/IOS-DFU-Library#134]
I just upgrade to the latest release. Before I was using 3.1.
Now things are - different. And I am still investigating.

What I can see is that the name changed to "DfuTarg". I don't understand why. And even more so I don't understand why I cannot revert this by flashing the original hex file via USB.

Pairing also seem to be behaving inconsistently.

I'll add more details when I have them.

**Comment by mostafaberg** [comment]
Peripherals in bootloader mode have the name DFUTarg you can't revert probably because you are flashing back an application that's not compatible with the soft device on the peripheral.

Please open an issue with all details so we can investigate right away next time.
