### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by developerXiong** [nordicsemi/IOS-DFU-Library#137]
I want to commit the code to Cocoapods, An error has occurred:
- WARN  | xcodebuild:  iOSDFULibrary/iOSDFULibrary/Classes/Implementation/DFUPeripheralSelector.swift:33:16: warning: 'select(_:advertisementData:RSSI:)' is deprecated

**Comment by mostafaberg** [comment]
No problems at all :)
Yes we are deprecating this method, you should use the new Select method instead, if you are not using this method at all, you don't need to do anything just use `allow-warnings` in your pod commands to bypass that, and we will eventually phase it out in a later release :)

**Comment by developerXiong** [comment]
I have used the allow-warnings command, but that mistake still exists:(

**Comment by mostafaberg** [comment]
What are you doing exactly ? can you show the commands you are using ?

**Comment by developerXiong** [comment]
pod trunk push MyProjectName.podspec --allow-warnings

**Comment by mostafaberg** [comment]
What version of cocoapods are you using ? `pod --version`

**Comment by developerXiong** [comment]
1.1.1

**Comment by mostafaberg** [comment]
first i would recommend using the latest version of cocoapods, second i think the problem is the ordering of the commands, I think this should work instead:
`pod --allow-warnings trunk push MyProjectName.podspec`

**Comment by developerXiong** [comment]
It's OK, you are best man, thank you!

**Comment by mostafaberg** [comment]
great to hear you got things working :) good luck!
