### ISSUE TITLE
Swift 3 migration

### ISSUE THREAD

**Issue by felipelmota** [nordicsemi/IOS-DFU-Library#138]
I having a issue trying to migrate to Swift 3. It is reproducing in 0.6.9 and 0.7.0 versions. ButtonlessDFU.swift 
"binary operator '+=' cannot be applied to operands of type 'Data' and 'String.UTF8View'"

**Comment by mostafaberg** [comment]
I'm not sure what you mean by Swift 3 migration ? our library is already in Swift 3 so you don't need to migrate it. and regarding your error , you are trying to use the `+=` operator on mismatching types of `Data` and `String.UTF8View` which is not going to work.

I would say just reintegrate the latest version `3.2.1` of the library into your project and you should be good to go, if you require help migrating your source code to Swift 3 you can take that to our Devzone where there are lots of others who will gladly help :), closing this as it is not an actual issue with the library
