### ISSUE TITLE
Missing @objc keyword to expose API to Objc

### ISSUE THREAD

**Issue by piellarda** [nordicsemi/IOS-DFU-Library#146]
Without the automatic inference from swift 3 some public methods are no longer expose to Objc.
For example in DFUServiceInitiator 
`public init(centralManager: CBCentralManager, target: CBPeripheral)`
and
`public func with(firmware file: DFUFirmware) -> DFUServiceInitiator`

**Comment by mostafaberg** [comment]
let's fix that !, sorry about this, will push a new fix soon

**Comment by piellarda** [comment]
Great, DFUFirmware and DFUServiceController public methods will have the same issues as well.

**Comment by mostafaberg** [comment]
Update is out, pushing to trunk now :)

**Comment by mostafaberg** [comment]
feel free to close the issue after you verify it works well for you :)

**Comment by piellarda** [comment]
It is working, thanks.
