### ISSUE TITLE
Support for Nordic SDK 12

### ISSUE THREAD

**Issue by lilliesAndRoses** [nordicsemi/IOS-DFU-Library#15]
Does the same library support upgrade with Nordik SDK 12? Do any APIs change?

**Comment by philips77** [comment]
The newest version should support Secure DFU and the legacy DFU. No API changes, except deprecating State in favor of DFUState and perhaps some small other...

**Comment by lilliesAndRoses** [comment]
Thanks. The description was updated for the Android library but not for iOS, hence the question!
