### ISSUE TITLE
Latest Zip (1.0.0) pod doesn't compile

### ISSUE THREAD

**Issue by casey-juul** [nordicsemi/IOS-DFU-Library#151]
I can't get the Zip Pod to compile with the latest iOSDFULibrary (4.0.2).

```/Volumes/Development/pax-app-ios/PaxApp/Pods/Zip/Zip/Zip.swift:174:118: Cannot convert value of type '[FileAttributeKey : Date]' to expected argument type '[String : Any]?'```

![image](https://user-images.githubusercontent.com/18601037/31208208-f6df8bce-a937-11e7-974d-c4deda26c86c.png)

**Comment by steffenmauch** [comment]
This is a problem of the Zip Pod; solution is given here https://github.com/marmelroy/Zip/pull/106/commits/ba620b25bff55a44770c00acb59ac8730e579221

**Comment by mostafaberg** [comment]
This issue has been resolved a long time ago in Zip, and is not really related to our library, so will close :), if you have any more issues let us know!

**Comment by cloudface** [comment]
I dont understand. When I install the cocoa pod for the DFU iOS library, it pulls the zip 1.0 pod with it which doesn't compile. How can I get the correct version of Zip that compiles when trying to install the DFU iOS library with cocoa pods?
