### ISSUE TITLE
i pod update and then convert swift3.0 ,there is error, the code is not support swift3.0 ?

### ISSUE THREAD

**Issue by xRuby** [nordicsemi/IOS-DFU-Library#18]
The newest code is not support swift3.0 ?

**Comment by sanderdb01** [comment]
I am in a similar boat. I have several dozen errors about the update. Will there be updated code? 

FYI, I ran pod update to get the latest code, is that the correct way to do it as of now? Thank you

**Comment by philips77** [comment]
Hi, @mostafaberg is coming back on Monday and will handle all issues then.

**Comment by mostafaberg** [comment]
The Swift 3.0 PR merge was done erroneously and has been reverted, work will be resumed this coming week and the update will be released in the same week!, at the current time, Swift 3.0 and the latest version of XCode are not supported!

**Comment by mostafaberg** [comment]
Work on Swift 3.0 migration is now resumed, will be ready within this week!

**Comment by mostafaberg** [comment]
[Swift 3.0 is now supported !](https://cocoapods.org/pods/iOSDFULibrary)

**Comment by sanderdb01** [comment]
So to update, should we just do pod update in the terminal after we update our podFile? When I did that, XCode gives me this error:
/Users/david/Projects/iOS Projects/Reverie/Reverie/DFUUpdateView.swift:11:8: Module file was created by an older version of the compiler; rebuild 'iOSDFULibrary' and try again: /Users/david/Library/Developer/Xcode/DerivedData/Reverie-dzbmxgfwzcovxtcabkyfiaygzabv/Build/Products/Debug-iphonesimulator/iOSDFULibrary.framework/Modules/iOSDFULibrary.swiftmodule/x86_64.swiftmodule

Any thoughts on what I might be doing wrong? Thanks a bunch

**Comment by mostafaberg** [comment]
@sanderdb01 Yes you'll just need that, but currently there's [an issue](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/issues/20) with v2.0 missing some filenames in the podspec, so it won't work, I'm currently working to get that updated ASAP

**Comment by sanderdb01** [comment]
I am also finding that my code can no longer find iOSLibrary when I import it. I look inside the Pods/iOSDFULibrary folder and there is only a README file and a LICENCE file, but no classes folder or anything else. I checked my old commits and that folder was there as well as in your source folder on github. I was wondering if there was something wrong with your CocoaPods setup, or perhaps I did something wrong. Thanks a bunch.

**Comment by klemenzagar91** [comment]
In other thread I got a reply. It their mistake and they'll solve it ASAP.

**Comment by mostafaberg** [comment]
Yes you'll see the issue in the comment above yours , currently downloading Xcode 8 again to do it from home, hang in there fix is on the way soon :)

**Comment by mostafaberg** [comment]
@sanderdb01 Can you give it a try with 2.0.1 now and let me know if things look ok ?

**Comment by sanderdb01** [comment]
It loads up the code great this time, thanks a bunch. I am still getting quite a few errors, but so far they seem to be on my end. I am also getting a warning on your files saying that it i smissing a working copy of several of your .swift files, but that might also be on my end. Let me do some cleaning and I will let you know. Thanks again for the great turnaround.
