### ISSUE TITLE
Outdated documentation (enable Unsafe Experimental Buttonless Service)

### ISSUE THREAD

**Issue by Drusy** [nordicsemi/IOS-DFU-Library#181]
The iOS README does not mention the way to enable the unsafe experimental buttonless service in secure DFU.

The Android README (https://github.com/NordicSemiconductor/Android-DFU-Library) says:
> This library is fully backwards compatible and supports both the new and legacy DFU. The experimental buttonless DFU service from SDK 12 is supported since version 1.1.0. Due to the fact, that this experimental service from SDK 12 is not safe, you have to call starter.setUnsafeExperimentalButtonlessServiceInSecureDfuEnabled(true) to enable it. Read the method documentation for details. It is recommended to use the Buttonless service from SDK 13 (for non-bonded devices, or 14 for bonded). Both are supported since DFU Library 1.3.0.

We can easily find this information in the example code but it would be nice to have it straightforward in the documentation related to the `DFU History`.
Something as simple as `initiator.enableUnsafeExperimentalButtonlessServiceInSecureDfu = true`.

**Comment by mostafaberg** [comment]
Adding that now :) thanks for pointing it out, this will come with some new changes and bugfixes in version 4.1.2
