### ISSUE TITLE
Differences between IOS-Pods-DFU-Library and IOS-DFU-Library repo?

### ISSUE THREAD

**Issue by huguesbr** [nordicsemi/IOS-DFU-Library#19]
I don't quiet get the difference between the two repos? 
Why do you have two, why not just one with tag for pods?
It seem they not updated at the same time, which one do you plan to maintain most actively?

https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/
https://github.com/NordicSemiconductor/IOS-DFU-Library/

Similar question on: https://github.com/NordicSemiconductor/IOS-DFU-Library/issues/49

Thanks

**Comment by mostafaberg** [comment]
Hi @huguesbr , sorry for the confusion, The `iOS-DFU-Library` is in the process of being deprecated in favor of Cocoapods and SPM, it will be left available for a short period until the `IOS-Pods-DFU-Library` contains the Swift 3.0 feature, and this will eventually be removed, they are supposed to be 1:1 with no changes but we always apply changes first on this repo before they are reflected on the Standalone library at `iOS-DFU-Library` repo.

I would say that you can completely ignore the old library and stick with the Cocoapods repository!
