### ISSUE TITLE
Strong reference cycle

### ISSUE THREAD

**Issue by DevAndArtist** [nordicsemi/IOS-DFU-Library#193]
I'm still in process of reading and understanding most of the internal code but I just noticed a potential issue. I say potential because it might already be resolved automatically at some point. If not then this is really an issue:

- https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/DFUServiceInitiator.swift#L258-L260-
- https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/DFUSelector/DFUServiceSelector.swift#L41
- https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/DFUServiceController.swift#L27

**Comment by philips77** [comment]
Hi, the strong reference is there intended, in order to be able to "start dfu and forget initiator and controller". It's broken when the dfu ends in either way. I hope.

**Comment by lovexiaoxia** [comment]
Hi,how do I after upgrade success or failure, release it?

**Comment by philips77** [comment]
It does it automatically on success or error. All deinit were called when I was testing it.
