### ISSUE TITLE
flash without pairing?

### ISSUE THREAD

**Issue by tcurdt** [nordicsemi/IOS-DFU-Library#195]
In a paired context we boot into DFU mode and then can successfully flash the device.
It seems that if we disable the need for pairing in the microbit firmware this does not seem to work.

While there might be good reasons not allowing flashing without pairing we are wondering if it should still be possible.

**Comment by mostafaberg** [comment]
it is indeed possible, pairing is up to the developer, the DFU process will work with/without pairing, you might want to check with MicroBit to see why it's not working in that case
