### ISSUE TITLE
Unable to add library with Cocoapods

### ISSUE THREAD

**Issue by cloudface** [nordicsemi/IOS-DFU-Library#197]
Hello

I am unable to add the DFU iOS library using Cocoapods. I added the following to my pod file:
`pod 'iOSDFULibrary'`
and ran pod install. When I tried to run my app, I got the following error:

<img width="1203" alt="screen shot 2018-06-06 at 15 05 49" src="https://user-images.githubusercontent.com/1231070/41040638-3b781686-699d-11e8-9bc6-eacaa2561764.png">

In my podfile.lock I noticed the following:
`- iOSDFULibrary (4.1.3): - Zip (~> 1.0)`

I saw that there was a new version of the Zip library (1.1.0). Maybe this issue has been fixed in that version of the library but I don't know how to get iOSDFULibrary to use the new version of Zip. How can I successfully add the iOSDFULibrary to my project using Cocoapods? Thanks guys.

**Comment by philips77** [comment]
Hi, @mostafaberg, who's maintaining the project is on vacations, but I'll try to help you tomorrow.

**Comment by cloudface** [comment]
Thanks @philips77 

In the meantime I did a bit of digging. My project is currently using Swift 3.2. I quickly created an empty Swift 4.0 app and installed the pod there and it worked. Do I have to upgrade my project to Swift 4.0 or is there a way to get it to work with Swift 3.2 projects? Is that even the root cause?

**Comment by philips77** [comment]
Apple deprecates old Swift versions quite quickly. I'd recommend using the latest version. There weren't many changes from 3.2 to 4, afair.

**Comment by mostafaberg** [comment]
@cloudface This issue is not related to our library, but the Zip dependency, from what I understand it seems to have been fixed, but we do recommend moving on to Swift 4.0 as soon as possible :)
