### ISSUE TITLE
alternativeAdvertisingNameEnabled and SDK 13

### ISSUE THREAD

**Issue by tompi** [nordicsemi/IOS-DFU-Library#198]
You are probably aware of this, but it caused us some grief.

The alternativeAdvertisingNameEnabled parameter defaults to true, and causes the updater to try and rename the device during dfu(secure dfu) which is only supported by sdk 14.

Our devices are at sdk 13, so this failed, but NOT for android devices, so you may want to do this like android lib has done it(not sure if it defaults to false there, or if it is able to sniff out sdk version somehow...)

Sorry to post a non-problem here, but I think it might save other some headaches in the future :)

**Comment by philips77** [comment]
On Android we don't use this feature, as there device address is available, so we base the device scan on address. On iOS we had to do this workaround to eliminate connecting to a wrong device. But you may force disable this feature by seeing this flash to false it your using sdk 13. Although, on sdk 13 it should try to set the name and fail, and resume without it, if you didn't do many changes in the bootloader. It you did, disable it.

**Comment by tompi** [comment]
OK, we did some changes yes(to enable updating other stuff than the BLE processor).

We set it to false and it works fine. (was just some extra hassle since we use xamarin, and the flag was relatively new, so not exposed in bindings :)

Thank you for quick response, I just figured if you KNOW the remote SDK is 13, you can ignore this flag, but you probably have no way of telling.

**Comment by philips77** [comment]
Yes... There is no way for us to know that. We know only after the request to set the name is rejected.
