### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by sdespont** [nordicsemi/IOS-DFU-Library#2]
Link under documentation is not working : 

> See the documentation for more information.

**Comment by mostafaberg** [comment]
Thanks for noting, This linked to the wrong documentation anyway and we don't have the one for Cocoapods ready yet, should've been left out, will fix that today, thanks !:)

**Comment by philips77** [comment]
For now use this link: https://github.com/NordicSemiconductor/IOS-DFU-Library/tree/master/documentation

**Comment by sdespont** [comment]
Ok, thanks

**Comment by mostafaberg** [comment]
Link is now fixed !
