### ISSUE TITLE
When updating to version 2.0 the library disappear.

### ISSUE THREAD

**Issue by klemenzagar91** [nordicsemi/IOS-DFU-Library#20]
<img width="478" alt="screen shot 2016-09-28 at 6 03 06 pm" src="https://cloud.githubusercontent.com/assets/5512848/18921650/ea6dc498-85a5-11e6-9f0c-31ea90b6752d.png">
<img width="264" alt="screen shot 2016-09-28 at 5 59 00 pm" src="https://cloud.githubusercontent.com/assets/5512848/18921662/f3f7223e-85a5-11e6-9a6d-71221372d1a4.png">

I'm also using xcode 8 for the first time. I'll try to solve this by myself, but just so you know there is maybe an issue on your side. As you can see, there is just LICENSE and README file in the folder.

**UPDATE**

I created an empty xcode project and the issue remain. I use the latest cocoapods pre-release version (https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.rc.2) that is recommended for xcode 8.

~~This guy claims to have found a solution for pods that use swift 3.0.
https://blog.sabintsev.com/submitting-swift-3-libraries-to-the-cocoapods-trunk-1-1-0-rc-2-2d07c22c9754#.ditdqbkd7~~ (I see you already make this)

**UPDATE 1**
And I case of having both xcode 7 and xcode 8 installed on a system you should run this:

> sudo xcode-select -switch /pathTo/Xcode8.app

 to make the xcode 8 the default app for generating pod. Here's the post about this:https://medium.com/@filipealva/cocoapods-lint-failing-with-xcode-8-a2c255e78108#.k3ql8n5cw

**UPDATE 2**
Tried your example file from git and and it also fails to run. Saying: No such module 'iOSDFULibrary'.

**Comment by mostafaberg** [comment]
Ouch, somehow managed to delete the sources in the podspec, will get that fixed ASAP!

**Comment by mostafaberg** [comment]
@klemenzagar91  Sorry for the delays, lots of configs, can you verify that it works now ? `2.0.1` wasjust released to fix this issue

**Comment by klemenzagar91** [comment]
aaaa it works :)

thank you

**Comment by mostafaberg** [comment]
That's great to hear!, thanks a lot for your feedback and sorry for the delays!
