### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by baiwanlu** [nordicsemi/IOS-DFU-Library#202]
IPhone version 8.2 uses the library to crash, the path that appears is the upgrade reached 20%,app back to the background for 10 seconds, and then into the foreground.

**Comment by philips77** [comment]
I tried it and it worked for me using the Example app. Could you give some logs?

**Comment by mostafaberg** [comment]
have you managed to resolve your issue ? if we do not hear back within the week we'll assume it's fixed and close the issue :)
