### ISSUE TITLE
OC project can not use pod install iOSDFULibrary

### ISSUE THREAD

**Issue by first-giver** [nordicsemi/IOS-DFU-Library#214]
hi,when I update iOSDFULibrary in my oc project,xcode has a few error.The pod can not find the ‘iOSDFULibrary’ lib.i test many times use different project,can you help me? if I had a mistake.thank you
![108321536823457_ pic_hd](https://user-images.githubusercontent.com/12823785/45474154-88d76000-b76b-11e8-889b-ce21d83f8f8c.jpg)

**Comment by first-giver** [comment]
hi，this is a supplement picture
![24d0601e-133f-49a0-a3d0-d54afce686c0](https://user-images.githubusercontent.com/12823785/45475944-55e39b00-b770-11e8-9ffb-fe1a92aca15a.png)

**Comment by mostafaberg** [comment]
still having the issue ? if we don' there back within next week we'll assume it's resolved and close the issue :)
