### ISSUE TITLE
Swift 4.2 update

### ISSUE THREAD

**Issue by MMooreGitHub** [nordicsemi/IOS-DFU-Library#215]
Good Day!

When can we expect this library to be updated for Swift 4.2?
I'm running XCOde 10 GM Seed  which uses this latest version of swift.
However, I'm reluctant to locally update the library to mitigate adverse  and unforeseen impacts.

**Comment by philips77** [comment]
Hi, 
I'll try to do this next week. But can't promise anything as well have some other projects to work on.

**Comment by zaxayn** [comment]
waiting for this update :)

**Comment by philips77** [comment]
So the macOS Mojave comes on 24 Sept. And I guess XCode 10 will be available together. We should wait for the final version, in my opinion.

**Comment by MMooreGitHub** [comment]
@philips77. Xcode 10 GM was released today (in the US at least). The BETA and seed versions were previously updated.
I'm running it on MacOS 10.13.6. The main thing Mojave introduces as it relates to Xcode is [Dark Mode]. I'm perfectly ok with waiting until 9/24. Thanks!

**Comment by philips77** [comment]
Yep, I got the update. See you on the other side! ;)

**Comment by andreyz** [comment]
@philips77 any update on Swift 4.2 timeline?

**Comment by haiztao** [comment]
@philips77 We are waiting for this update :)

**Comment by philips77** [comment]
@mostafaberg ?

**Comment by arthare** [comment]
Depending on your level of desperation, I found it wasn't that hard to clone and build the iOSDFULibrary.framework with swift 4.2 in XCode 10 as a stopgap until official support is available.  There didn't appear to be any significant code changes required.  But I'm also a bit of a newbie for iOS development, so I may have missed something.

**Comment by andreyz** [comment]
@philips77 @mostafaberg any timeline for official release?

**Comment by philips77** [comment]
Hi, porting to 4.2 was easy, but the #206 did break some things so we need to fix it before releasing. We are now both busy with some other things... I'll try to look into it tomorrow. Sorry for the delay!

**Comment by philips77** [comment]
Check out #225 and #227

**Comment by andreyz** [comment]
@philips77 what does that mean?

**Comment by MMooreGitHub** [comment]
@andreyz- Essentially, it means there are two related issues which the team is diligently working on. They are also busy with other activities. So, we just need to be patient and respect this.

**Comment by philips77** [comment]
We'll try to release it today as 4.2.
@andreyz it didn't sound like you were asking for ETA, sorry. I see there are couple of open issues on GitHub, i need to check them first.

**Comment by andreyz** [comment]
@philips77 thanks for the update.

**Comment by philips77** [comment]
Version 4.2 with Swift 4.2 is out (Coincidence? I don't think so!). 
Closing the issue new. If you have any troubles, feel free to open a new issue and describe it there.
