### ISSUE TITLE
Xcode 8 asks to convert Swift for 2.1.1

### ISSUE THREAD

**Issue by kklobe** [nordicsemi/IOS-DFU-Library#22]
After installing successfully (pod install verifies iOSDFULibrary 2.1.1 and Zip 0.6.0), Xcode 8 still asks me to convert to latest Swift syntax for iOSDFULibrary and Zip when opening the workspace.

Should this be working for Xcode 8?

**Comment by mostafaberg** [comment]
You need to have the latest RC of Cocoapods installed for Swift3 support
`sudo gem install cocoapods --pre`

**Comment by kklobe** [comment]
Well, that was easy - thanks!

**Comment by mostafaberg** [comment]
No worries 👍  , hopefully soon you won't need a prerelease to build Swift 3 projects!
