### ISSUE TITLE
pod install Swift  Swift version

### ISSUE THREAD

**Issue by Vinvinda** [nordicsemi/IOS-DFU-Library#223]
[!] Unable to determine Swift version for the following pods:

 - `Zip` does not specify a Swift version and none of the targets (`RoWrite`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.\n- `iOSDFULibrary` does not specify a Swift version and none of the targets (`RoWrite`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

I have encountered this problem,  help me. thank you

**Comment by mostafaberg** [comment]
Are you still having This issue ? what I would do (until we release the Swift 4.2 version) is to go into your project's settings and go to the Zip Target and iOSDFULibrary target and set `SWIFT_VERSION` in the settings to `latest`

**Comment by quanyou** [comment]
Did you resolve your problem?

**Comment by haoyuant** [comment]
I have the same issue, any solution?

**Comment by DataCenterSource** [comment]
Is there any solution now? I meet the same problem after "pod install".
many thanks

[!] Unable to determine Swift version for the following pods:

- `Zip` does not specify a Swift version and none of the targets (`MyApp`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
- `iOSDFULibrary` does not specify a Swift version and none of the targets (`MyApp`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by DataCenterSource** [comment]
Is there any solution now? I meet the same problem after "pod install".
many thanks

[!] Unable to determine Swift version for the following pods:

Zip does not specify a Swift version and none of the targets (MyApp) integrating it have the SWIFT_VERSION attribute set. Please contact the author or set the SWIFT_VERSION attribute in at least one of the targets that integrate this pod.
iOSDFULibrary does not specify a Swift version and none of the targets (MyApp) integrating it have the SWIFT_VERSION attribute set. Please contact the author or set the SWIFT_VERSION attribute in at least one of the targets that integrate this pod.

**Comment by philips77** [comment]
In version [4.3.0](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/releases/tag/4.3.0) we switched from dependency Zip to ZipFramework. You need to [update your CocoaPods](https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods) to at least 1.7 (I think) to use be able to use the latest versions.
