### ISSUE TITLE
get output frames failed, state 8196

### ISSUE THREAD

**Issue by HongCongZhi** [nordicsemi/IOS-DFU-Library#235]
<img width="430" alt="2018-10-08 4 50 38" src="https://user-images.githubusercontent.com/19814616/46599609-5d515680-cb1a-11e8-8664-d0569fd5a33a.png">
why？

**Comment by mostafaberg** [comment]
No clue, those logs are not related to our DFU library :).
You most probably have other code that's running an SSL request or something that's causing this.

**Comment by HongCongZhi** [comment]
> No clue, those logs are not related to our DFU library :).
> You most probably have other code that's running an SSL request or something that's causing this.

I used DFU in IOS-nRF-Toolbox and prompted "Scanning for the DFU Bootloader ...", it didn't respond.
