### ISSUE TITLE
Compatibility with AlamoFire Download and internet connections

### ISSUE THREAD

**Issue by MMooreGitHub** [nordicsemi/IOS-DFU-Library#255]
Hi @mostafaberg 

Are you aware of any incompatibility issues between the DFU library and using Alamofire.Download?
(https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#downloading-data-to-a-file)

Once I connect to the Central Manager. For example within the ViewDidAppear and call the 
[Asyncronous] Alamofire.Download task to download a file from the internet , it constantly does not return my download data.
I verified this I am able to download without problem using a sample app which does not perform BlueTooth connections and operations such as the DFU library does.

**Comment by philips77** [comment]
Did you try setting a different queue in DfuServiceInitiator's init?

**Comment by mostafaberg** [comment]
We do not have any compatibility issues and I don't see how our library would affect your code.

can you show some code where he issues occur ?

**Comment by philips77** [comment]
I'll close the issue due to inactivity. Please, feel free to reopen or create another one if needed.
