### ISSUE TITLE
 Unable to determine Swift version for the following pods

### ISSUE THREAD

**Issue by 179992096** [nordicsemi/IOS-DFU-Library#276]
[!] Unable to determine Swift version for the following pods:

- `Zip` does not specify a Swift version and none of the targets (`Cheetah`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by philips77** [comment]
Duplicate of #268.
