### ISSUE TITLE
iPhone8以上手机出现Operation not permitted

### ISSUE THREAD

**Issue by ColaColeChao** [nordicsemi/IOS-DFU-Library#280]
您好，我们在iphone7和之前的手机上使用这个动态库没有问题，但是在iPhone8和iPhone8以后的手机上使用，可以更新，但是，每次更新一点就会报错Operation not permitted，之后再连接蓝牙在升级一点还会报错Operation not permitted，不知道是不是手机读取升级包的权限问题还是其他问题，望解答。另外，在appstore上下载的官方app同样会有这个问题

**Comment by philips77** [comment]
Check out #319.
