### ISSUE TITLE
problem with pods install 

### ISSUE THREAD

**Issue by mrarkadiys** [nordicsemi/IOS-DFU-Library#282]
Hi! After trying to install pods I receive these errors and .workspace file doesn't appear. Pod file is exactly the same as in instruction. Can you help me with? 

[!] Unable to determine Swift version for the following pods:

- `ZIPFoundation` does not specify a Swift version and none of the targets (`TEST_IOS_Ble`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
- `iOSDFULibrary` does not specify a Swift version and none of the targets (`TEST_IOS_Ble`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

<img width="778" alt="Снимок экрана 2019-03-31 в 9 26 45" src="https://user-images.githubusercontent.com/48833102/55285560-28221480-5397-11e9-8790-a89ce72458af.png">

**Comment by philips77** [comment]
It looks like the SWIFT_VERSION build setting must be defined in the app target prior to invoking pod install.

Check out this: https://github.com/CocoaPods/CocoaPods/issues/7770

**Comment by philips77** [comment]
Hi, did you manage to solve your issue?

**Comment by iwown** [comment]
@philips77  Hello, I had meet the same issue. Cocoapods advise "Add swift_version to podspec", 
 but .podspec is not a file in my project. How can I do for it ?

**Comment by mrarkadiys** [comment]
@philips77, yes , your link helped me to solve it, thank you! Sorry for long silent.

**Comment by mrarkadiys** [comment]
Hi @iwown ! All you need to do is : 
1) Go to your target settings -> build settings
2) Then click plus - > add user defined settings 
3) (scroll down if lost it) Name the setting as SWIFT_VERSION and set a key value as 3.2 (or other value, but this one worked for me)   
<img width="627" alt="Снимок экрана 2019-04-15 в 18 50 31" src="https://user-images.githubusercontent.com/48833102/56137990-5b77bc80-5faf-11e9-905f-cfa80b96a59e.png">
<img width="495" alt="Снимок экрана 2019-04-15 в 19 06 12" src="https://user-images.githubusercontent.com/48833102/56139064-8bc05a80-5fb1-11e9-9158-601cdaffbcde.png">

**Comment by iwown** [comment]
Thank you for response .I had fix this issue by update lib to *pod 'iOSDFULibrary', '~ 4.4.1* .


原始邮件
发件人:Aleksander Nowakowskinotifications@github.com
收件人:NordicSemiconductor/IOS-Pods-DFU-LibraryIOS-Pods-DFU-Library@noreply.github.com
抄送:Iwown ShenZhenappdev@iwown.com; Mentionmention@noreply.github.com
发送时间:2019年4月19日(周五) 18:01
主题:Re: [NordicSemiconductor/IOS-Pods-DFU-Library] problem with podsinstall (#282)


Closed #282.

**Comment by yexiaofeiut** [comment]
> Thank you for response .I had fix this issue by update lib to *pod 'iOSDFULibrary', '~ 4.4.1* . 原始邮件 发件人:Aleksander Nowakowskinotifications@github.com 收件人:NordicSemiconductor/IOS-Pods-DFU-LibraryIOS-Pods-DFU-Library@noreply.github.com 抄送:Iwown ShenZhenappdev@iwown.com; Mentionmention@noreply.github.com 发送时间:2019年4月19日(周五) 18:01 主题:Re: [NordicSemiconductor/IOS-Pods-DFU-Library] problem with podsinstall (#282) Closed #282. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

but it's not work for me!
