### ISSUE TITLE
name conflict

### ISSUE THREAD

**Issue by JuannyiOS** [nordicsemi/IOS-DFU-Library#283]
When these two libraries are added manually，error:'CRC32' is ambiguous for type lookup in this context

final class CRC32: Hashable  in crc32.swift
public typealias CRC32 = UInt32  in Data+Compression.swift 

private let crcTable: [UInt32]  in crc32.swift and  Data+Compression.swift

**Comment by philips77** [comment]
What other library are you using?
I'll be releasing an update to the DFU lib with Swift 5 migration, I can either rename the CRC32 to something else, or make it internal. Or both. I will have to check if it doesn't break backwards compatibility.

**Comment by ttlock** [comment]
only these two libraries

**Comment by philips77** [comment]
Fixed in 4.4.0.
