### ISSUE TITLE
Issue with notification 

### ISSUE THREAD

**Issue by sawanmind** [nordicsemi/IOS-DFU-Library#292]
I am getting the following error.

Error:==> Enabling notifications failed
Error:==> Error 6: The request is not supported.
Can anyone let me know what's wrong?

Code:

```swift    
        guard let firmware = firmwareProvider?.firmware else {
            Logs.shared.log.value.append("No firmware found")
            return
        }
        
        let initiator = DFUServiceInitiator(queue: DispatchQueue(label: "microbit_flushing"))
        initiator.logger = self
        initiator.delegate = self
        initiator.progressDelegate = self
        initiator.forceDfu = true
        initiator.enableUnsafeExperimentalButtonlessServiceInSecureDfu = true
        
        let dfu_uuid = [DFUUuid(withUUID: GATTKey.DFUServiceUUID, forType: .buttonlessService),
                        DFUUuid(withUUID: GATTKey.DFUCharacteristicUUID, forType: .buttonlessCharacteristic)]
        
        initiator.uuidHelper = DFUUuidHelper(customUuids: dfu_uuid)
        
        if #available(iOS 11.0, macOS 10.13, *) {
            initiator.packetReceiptNotificationParameter = 0
        }
        
        
        firmwareProvider?.applyModifier(to: initiator)
        
        
        
        if let _ = self.getPath(of: "abc"), let target = self.blePeripheral {
            //            let firmware = self.didSelectFirmwareType(.softdeviceBootloaderApplication, selectedFileURL: url) {
            //            print(firmware.parts)
            self.dfuController = initiator.with(firmware: firmware).start(target:target)
        }
```

for performing DFU

**Comment by philips77** [comment]
I understand that your device is using non-standard UUIDs. Are you sure you are setting correct services for buttonless service and its characteristic? Seems like you are setting the DFU service and DFU characteristic UUIDs for buttonless service.
Does your characteristic have Client Characteristic Configuration Descriptor (CCCD) and supports Indications/Notifications?

**Comment by sawanmind** [comment]
Hi @philips77,
Thanks for replying.
I am new to Microbit.
I am afraid. What do you mean by non-standard UUIDs? and how shall I know characteristic have CCCD.

**Comment by sawanmind** [comment]
Hi @philips77 ,
I figure out what is CCCD. Now I am getting errors like below.


application:==> Buttonless DFU notifications enabled

warning:==> Application with buttonless update found

State changed to: Enabling DFU Mode

verbose:==> Writing to characteristic E97D3B10-251D-470A-A062-FA1922DFA9A8...

debug:==> peripheral.writeValue(0x01, for: E97D3B10-251D-470A-A062-FA1922DFA9A8, type: .withResponse)

error:==> Writing to characteristic failed

error:==> Error 3: Writing is not permitted.

verbose:==> Disconnecting...

debug:==> centralManager.cancelPeripheralConnection(peripheral)

debug:==> [Callback] Central Manager did disconnect peripheral

info:==> Disconnected

**Comment by sawanmind** [comment]
@philips77 
Thanks in advance.
I would like to know, what am I doing wrong?

**Comment by philips77** [comment]
Hi, sorry that you had to wait that long. Did you manage to solve your problem?

**Comment by philips77** [comment]
Closing the issue due to inactivity.
