### ISSUE TITLE
any hint about `DFUErrorDeviceNotSupported`

### ISSUE THREAD

**Issue by LiuMengzhou** [nordicsemi/IOS-DFU-Library#294]
Sorry to bother.
I got an error like this:
![image](https://user-images.githubusercontent.com/13726966/56261080-45cbd980-610c-11e9-81c3-e3ce77f8fbe2.png)
Any hint about this?
Thanks in advance!!!

**Comment by philips77** [comment]
This https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/4a2b9c0f21cdbfde6893dfbe6bf3777ed9b05d4a/iOSDFULibrary/Classes/Implementation/DFUServiceDelegate.swift#L88 error is thrown when the device you connect to does not have supported DFU service nor Buttonless DFU service.
