### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by alwaleedalabri** [nordicsemi/IOS-DFU-Library#305]
I'm having issue while installing my pod file, error is the following: 

[!] Invalid `Podfile` file: syntax error, unexpected end-of-input, expecting keyword_end.

 #  from /Users/asa/Desktop/PROJECT/IFNTTN/Podfile:28
 #  -------------------------------------------
 #    end
 > 

Thanks,

**Comment by philips77** [comment]
Well... You have to fix your Podfile then.
