### ISSUE TITLE
Catching data before it is written 

### ISSUE THREAD

**Issue by siddarthgandhi** [nordicsemi/IOS-DFU-Library#306]
Is there a way I can get the stream data, wrap it with my own header to each part and then write it to a bluetooth device manually?

**Comment by philips77** [comment]
No, there is no such feature in the library. Only the standard Nordic Dfu is supported, where the lib is doing all the connection and transfer.
May I ask why do you need this?

**Comment by siddarthgandhi** [comment]
For secure transport of data over bluetooth.

**Comment by philips77** [comment]
If you are using Secure DFU, the protocol ensures that the fw received on the device will be authenticated. The init packet is signed and it contains the hash of the fw.

**Comment by siddarthgandhi** [comment]
We're using that too!
