### ISSUE TITLE
Using the Swift language is banned in our company

### ISSUE THREAD

**Issue by guo846773272** [nordicsemi/IOS-DFU-Library#312]
Hello, As the title suggests,at the present stage,Using the Swift language is banned in our company. 😂 Now we need to implement OTA functionality in Objective-C?But,I can't finish the OTA implementation, 🙃 Is there any library I can use?Thank you very much

**Comment by philips77** [comment]
You may check some very, very old branches or commits, when this lib was in O-C. But most features are not supported there and there's plenty of bugs. We recommend banning objective c.

**Comment by DevAndArtist** [comment]
@guo846773272 I feel really sorry for your company. You need to convince your org to switch. I think Apple will slowly fade out Objective-C usage now that Swift has ABI stability.
