### ISSUE TITLE
can't pod

### ISSUE THREAD

**Issue by yexiaofeiut** [nordicsemi/IOS-DFU-Library#315]
[!] Unable to determine Swift version for the following pods:

- `Zip` does not specify a Swift version and none of the targets (`CloudLock`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by philips77** [comment]
Have a look at this issue: #282. 
Also, we recommend switching to the latest version of the DFU Library, which switched to ZIPFramework instead of ZIP, and this issue does not exist there.
