### ISSUE TITLE
'Zip' dependency not handled for Carthage users

### ISSUE THREAD

**Issue by jakerockland** [nordicsemi/IOS-DFU-Library#32]
Currently this library doesn't have a Cartfile to address the 'Zip' dependency for Carthage users. I've made a small patch at #31, which is still a work in progress.

**Comment by jakerockland** [comment]
This is handled I believe by #33 if the Example directory is deleted after Carthage has already built the framework. Otherwise, there will be a build error due to a conflict between all of the files from the 'Zip' library that have been manually copied to the Example directory and the library itself when checked out with Carthage. Not 100% sure how to resolve this. @mostafaberg

**Comment by mostafaberg** [comment]
Yes this seems to be the case, will review your PR and update the fix hopefully during this week!

**Comment by jakerockland** [comment]
Awesome, thanks so much @mostafaberg 👍 😄

**Comment by mostafaberg** [comment]
Fixed now with help from @jakerockland 's PR #33 :)
