### ISSUE TITLE
OC Project pod was not successful. Ask for help ~

### ISSUE THREAD

**Issue by QionglinFu1024** [nordicsemi/IOS-DFU-Library#321]
~/Desktop/libTool/demo   master  pod install
Analyzing dependencies
Downloading dependencies
Installing ZIPFoundation (0.9.8)
Installing iOSDFULibrary (4.3.0)
[!] Unable to determine Swift version for the following pods:

- `ZIPFoundation` does not specify a Swift version and none of the targets (`demo`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
- `iOSDFULibrary` does not specify a Swift version and none of the targets (`demo`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by philips77** [comment]
Please, use the latest version of dfu library, which is 4.4.2.
