### ISSUE TITLE
[Pod-SDK-v4.4.2]Always got an error in iOS 13 beta when start DFU!

### ISSUE THREAD

**Issue by GrayLand119** [nordicsemi/IOS-DFU-Library#322]
It works fine in iOS12 but in iOS 13 beta, it got an error.
In iOS13 beta, after sending the specified firmware to the given DFU target, the delegate method will invoke, `- (void)dfuError:(enum DFUError)error didOccurWithMessage:(NSString * _Nonnull)message`, and the error and message is:
```objc
(lldb) po error
DFUErrorBluetoothDisabled

(lldb) po message
Could not obtain peripheral instance
```

Part of my codes are below:

```objc
dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);
DFUServiceInitiator *initiator = [[DFUServiceInitiator alloc] initWithQueue:queue delegateQueue:queue progressQueue:queue loggerQueue:queue];
initiator = [initiator withFirmware:selectedFirmware];
initiator.logger           = self;
initiator.delegate         = self;
initiator.progressDelegate = self;

__unused DFUServiceController *controller = [initiator startWithTarget:connectedDFUDevice.peripheral];
```

**Comment by philips77** [comment]
Thanks for the report. I'll have to try it on iOS 13.

**Comment by tkach** [comment]
I've got the same problem, works fine on versions prior to iOS 13, but I get this error on iOS 13 (Beta 4).
My code of starting the DFU is very similar to what @GrayLand119 posted.

Part of the logs that are printed to console when `startWithTarget:peripheral ` is called and we get the error:

```
default	12:01:10.194677 +0300	bluetoothd	Received XPC message "CBMsgIdTCCDone" from session "com.[hidden]-central-1654-4122"
default	12:01:10.194753 +0300	bluetoothd	App <private> was built with SDK c0200
default	12:01:10.194835 +0300	bluetoothd	Received XPC message "CBMsgIdRetrievePeripheralsWithIdentifiers" from session "com.[hidden]-central-1654-4122"
error	12:01:10.194902 +0300	bluetoothd	Ignoring XPC message as state is "Unknown"
default	12:01:10.195912 +0300	[hidden_app_name] Error from iOS-DFU-Library : Could not obtain peripheral instance

```

This line is *only* printed to console when app is running iOS 13 (I don't see it on older iOS versions).
`	bluetoothd	Ignoring XPC message as state is "Unknown"`

Probably something had changed in bluetoothd in iOS 13 and it's now mandatory to wait before the state `CBCentralManager` becomes `poweredOn` before calling the`retrievePeripheralsWithIdentifiers:` func [here](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/6ef3aa5afe100e2087ed1cdeefad7a504b224faf/iOSDFULibrary/Classes/Implementation/DFUServiceInitiator.swift#L398)?

As a workaround I've tried to set a few seconds delay between initializing the `DFUServiceInitiator`  and calling `func start(target: CBPeripheral)`, and I'm able to start the DFU without this error, however BLE communication fails later (idk maybe there are similar issues at some other parts of the library or my code) but may work for you @GrayLand119

**Comment by GrayLand119** [comment]
Thanks, @tkach, It works for me.

**Comment by tkach** [comment]
I'm glad it helped. 
@GrayLand119 Could you please reopen this issue as the workaround helps in testing purposes but doesn't seem to be the right solution for production use?

**Comment by GrayLand119** [comment]
Ok, the issue is reopened.

**Comment by philfi** [comment]
Hi just curious if there's any follow up on this? I noted this issue as well: https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/issues/313 but seem this thread has done a bit more digging into the underlying cause/possible workarounds in iOS 13 beta. Still seeing these crashes from users running iOS 13 beta 7 so seems this may be something that needs updated in the library vs a bug in iOS 13 beta. If necessary I may have some time on my plate next week to help dig into possible solutions.

**Comment by philips77** [comment]
Yes, we're aware of this issue. I'll fix it this week, most probably on Wednesday.

**Comment by philfi** [comment]
Thanks for the update!

**Comment by philips77** [comment]
This should be now working with version 4.5.1. Thanks for the great feedback, Everyone.

**Comment by bojennett** [comment]
So, why can't we get 4.5.1 on CocoaPods?  It maxes out at 4.3.0.  Is CocoaPods not supported anymore?

**Comment by philfi** [comment]
@bojennett It is available on Cocoapods, can you give more specific details on the issue you're seeing? You may just need to run a `repo update`, that doesn't happen automatically on `install` or `update` commands anymore.

**Comment by bojennett** [comment]
Looks like I had to update cocoapods (via gem).  I had 1.7.5.  When I updated (1.8.3), it pulled the latest iOSDFULibrary, and I can confirm it is working for me now!  Thanks.

**Comment by bojennett** [comment]
when I ran `pod install` with my 1.7.5 pod command, it pulled the 4.3.0.  When I updated to 1.8.3 and ran `pod install`, it pulled the 4.5.1 and swapped out Zip for ZipFoundation.
