### ISSUE TITLE
Silent retry for failed DFU and DFUServiceController should be able to resume/ restart after failed DFU

### ISSUE THREAD

**Issue by PinichTrio** [nordicsemi/IOS-DFU-Library#332]
Currently when DFU fails  I do receive error (`func dfuError(_ error: DFUError, didOccurWithMessage message: String)` which is the error delegate method), but I'm unable to restart or resume DFU.
The device stays in DFU state and I can't find it with the regular filters (Filtering by services).
I tried to use `DFUServiceController` but when the error occurs this instance of the dfuServiceController is useless.
I don't believe that I'm the only one who encountered this issue.
Any suggestions will be very appreciated

**Comment by philips77** [comment]
Released in 4.6.0. Hope it will work for you! Please test and let me know :)
