### ISSUE TITLE
iOS 13 Update failed.

### ISSUE THREAD

**Issue by ChaosYang** [nordicsemi/IOS-DFU-Library#335]
The centralManager.retrievePeripherals has 0 elements. 
` guard let peripheral = self.centralManager.retrievePeripherals(withIdentifiers: [uuid]).first else {
            delegate?.dfuError(.bluetoothDisabled, didOccurWithMessage: "Could not obtain peripheral instance")
            return nil
        }`
Return nil. Update failed.

**Comment by philips77** [comment]
Are you using the latest version of the library? This has been fixed recently.

**Comment by ChaosYang** [comment]
> Are you using the latest version of the library? This has been fixed recently.

Yes, the version I am using is the latest ----- 4.2.2

**Comment by philips77** [comment]
The latest version is 4.5 1.

**Comment by ChaosYang** [comment]
> The latest version is 4.5 1.

Ohh. The latest version I searched for is 4.4.2 and I will try again with the latest version. thank you very much. But i didn't search the version 4.5.1.

**Comment by philips77** [comment]
https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/releases
