### ISSUE TITLE
Can version 4.5.1 support swift5.1?

### ISSUE THREAD

**Issue by haiztao** [nordicsemi/IOS-DFU-Library#336]
I want to upgrade Xcode to 11，but don't know version 4.5.1 is support swift5.1 ?

**Comment by philips77** [comment]
We will migrate very soon. This should already work with 5.1 but hasn't been tested.

**Comment by DevAndArtist** [comment]
@haiztao @philips77 As far as I can tell this version is supported by Swift 5.1. (I haven't migrated to SPM yet, but Carthage has no issues so far.)

**Comment by philips77** [comment]
I just tried creating a test project with Xcode 11 and SwiftUI and adding this library as dependency using SPM and had no issues. thanks @DevAndArtist for testing.
