### ISSUE TITLE
DFU does not work anymore since iOS 13

### ISSUE THREAD

**Issue by mickaelhero** [nordicsemi/IOS-DFU-Library#341]
Since iOS 13 the dfu no longer works. I get `error 203` from DFUError 203 it's `bluetooth disabled`. Why? before ios 13 that worked.

When I try to launch the DFU from NRF Connect application. It is disconnected directly. Is there a problem with iOS 13?

This is my initiator:
```
func startUpdateDFU(with peripheral: CBPeripheral, zipFilePath: URL, completion: DFUCompletion? = nil) {
        guard let firmware = DFUFirmware(urlToZipFile: zipFilePath) else {
            return
        }

        dfuHandler = completion

        let initiator = DFUServiceInitiator(queue: nil).with(firmware: firmware)
//        initiator.forceDfu = true
        initiator.alternativeAdvertisingNameEnabled = false // Must be true, if not work set it to false!
        initiator.delegate = self
        initiator.progressDelegate = self
        initiator.peripheralSelector = self
        initiator.logger = self

        dfuController = initiator.start(target: peripheral)
    }
```

**Comment by bojennett** [comment]
I, too, am having this problem.

After sending the start, I immediately get a `dfuError` with code 203 "Could not obtain peripheral instance".

The same code when running on an iOS12 (or 11, or 10) device works just fine.

**Comment by bojennett** [comment]
will somebody... anybody.. from Nordic at least COMMENT on this?  This is ridiculous.

**Comment by BlackMonkeyidea** [comment]
@bojennett @mickaelhero 
I found that this library has solved the problem in version 4.5.1.
I tried to update the library and can upgrade DFU normally.
#322

**Comment by mickaelhero** [comment]
@BlackMonkeyidea Thank you, now it works, but it's disappointing on the part of Nordic not to have had an answer on this issue after 5 days!

**Comment by bojennett** [comment]
so the problem I guess then is that cocoa pods for iOSDFULibrary seems to max out at 4.3.0

**Comment by philips77** [comment]
No, just change the version on your podfile to 4.5.1.

**Comment by philips77** [comment]
@mickaelhero Sorry for not replying, I'm on vacations this week. But if you'd check closed issues in this repo there already were 2 or 3 issues related to iOS 13 issue. 4.5.1 was released before 13 went public.
