### ISSUE TITLE
Version 4.5.1 is still unable to adapt to swift 5.1

### ISSUE THREAD

**Issue by haiztao** [nordicsemi/IOS-DFU-Library#342]
I've upgraded from Carthage to version 4.5.1, but I still can't run swift 5.1 to warn of errors.

**Comment by haiztao** [comment]
> I've upgraded from Carthage to version 4.5.1, but I still can't run swift 5.1 to warn of errors.
![1571105176828](https://user-images.githubusercontent.com/13958064/66794468-36e7a780-ef34-11e9-8dd1-00f03795d8e3.jpg)
![1571105137567](https://user-images.githubusercontent.com/13958064/66794472-3bac5b80-ef34-11e9-805c-a862177af771.jpg)

**Comment by philips77** [comment]
We'll update dfu library soon.

**Comment by ghost** [comment]
Hey Philips,

Any ETA on the iOS DFU library update ?

Thanks.

**Comment by philips77** [comment]
Isn't Carthage compiled on your machine? Shouldn't you just call `carthage update` command and drag new binaries from *Carthage/Build/<platform>*?
See: https://github.com/Carthage/Carthage

**Comment by philips77** [comment]
Have a look at: https://stackoverflow.com/a/58621404

**Comment by philips77** [comment]
@DevAndArtist, could you help here? The version 4.5.1 works for you with Carthage.

**Comment by DevAndArtist** [comment]
I don't exactly know what's wrong here, you could check if you use correct Xcode in case if you have multiple versions. The error messages seems to indicate that you compile with an older version of Xcode.

https://stackoverflow.com/a/37868983

Also which Carthage version do you use? (Update it if it's outdated.)

**Comment by philips77** [comment]
Thanks! @haiztao @had23j you may also check out the first comment on the link above: https://stackoverflow.com/questions/37867753/change-carthage-swift-version/37868983#comment78202856_37868983 (this is if you don't want to play with console).

**Comment by haiztao** [comment]
> Thanks! @haiztao @had23j you may also check out the first comment on the link above: https://stackoverflow.com/questions/37867753/change-carthage-swift-version/37868983#comment78202856_37868983 (this is if you don't want to play with console).

**Comment by haiztao** [comment]
@philips77 Hi philips77 Have you tried to update to Xcode 11 and swift 5.1.See if it fits

**Comment by philips77** [comment]
Yes, I'm using Xcode 11 and Swift 5.1.

**Comment by philips77** [comment]
I just released 4.6.0, which is developed in Xcode 11 with Swift 5.1.
