### ISSUE TITLE
Legacy DFU failing

### ISSUE THREAD

**Issue by RFz2** [nordicsemi/IOS-DFU-Library#357]
Hello,

We are having trouble updating existing products running legacy DFU on NRF51 with the latest version of this library. Attached are the user logs.

[user_log.txt](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/files/4064542/user_log.txt)

Legacy DFU works on Android.

We are using ZIP package containing the hex and init files on iOS. The issue appears to affect the iOS Nordic Connect app also.

Any help is appreciated.

Thanks Ryan

**Comment by RFz2** [comment]
Hello,

Have you experienced any issues like I explained above? It is only affecting our legacy DFU devices on iOS.

Appreciate if you could let us know if this is a known issue.

Regards
Ryan

**Comment by philips77** [comment]
Nope, we didn't. We also didn't hear from anyone else... Are you able to replicate it using the samples from SDK?

**Comment by philips77** [comment]
Hi, did you manage to solve your issue?

**Comment by jhays** [comment]
I think I am running into this same issue. 

I am using an nRF52 dev kit board running nordic's HRM with buttonless DFU sample app on SDK 11. After I connect to it from iOS, I ask this lib to kick off the DFU process. My log looks very similar to OP's- I am stuck in an infinite loop of connect, discover, initiate, disconnect, connect.... 

If anyone has any suggestions I'd greatly appreciate it.

**Comment by philips77** [comment]
What phone are you using on and what's the iOS version?
Are you using bonding?

**Comment by philips77** [comment]
You device seems to disconnect on enabling notifications. It you're using bonding, and you removed bond info on one side, make sure you removed it also in the other.

**Comment by jhays** [comment]
Ultimately I think my issue was misconfiguration of my dev kit board. After updating the bootloader I believe I have resolved my issue.

**Comment by philips77** [comment]
Great! Good luck with the project!
