### ISSUE TITLE
Guarantee word-aligned writes to the packet characteristic

### ISSUE THREAD

**Issue by SuhaibI** [nordicsemi/IOS-DFU-Library#358]
After some modification of the DFU flow, I'm getting into some interesting cases where the MTU negotiation fails to guarantee word-aligned characteristic writes. Would it be possible to force this on the iOS side by changing:
```
packetSize = UInt32(characteristic.service.peripheral.maximumWriteValueLength(for: withoutResponse))
```
in SecureDFUPacket.swift line 61 to:
```
// Make the packet size the first word-aligned value that's less than the maximum
packetSize = UInt32(characteristic.service.peripheral.maximumWriteValueLength(for: .withoutResponse)) & 0xFFFC
```
I've tested this locally, and it seems to work, but I don't want to mirror and maintain this repo.

**Comment by philips77** [comment]
Interesting case. Please, create the PR and we will merge it.

**Comment by philips77** [comment]
What modifications did you make in the DFU?
By default, iOS sets the maximum write value length to 247, at least on iPhone 11, and this seems to be working for me. Setting `packetSize` to 244 will slow down upload speed by 1%.

**Comment by philips77** [comment]
Have a look at #366. But before I merge, please clarify why it is needed and why the default behavior does not work for you.

**Comment by philips77** [comment]
Ping?

**Comment by SuhaibI** [comment]
Sorry - missed your pings. Commented #366. Let me know if my comment makes sense, and you have any further questions.
