### ISSUE TITLE
Fatal error:Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by longhunpeter** [nordicsemi/IOS-DFU-Library#362]
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/mac/iosWorkSpance/IOS-Asthma-New/asthma/Pods/iOSDFULibrary/iOSDFULibrary/Classes/Implementation/DFUServiceInitiator.swift, line 272。

**Comment by philips77** [comment]
Which version of the library are you using? The latest one is 4.6.1 and there's nothing on line 272 in that file:
https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/b7be7a01a2a71070fb56ade7d4628ef6c6e0d162/iOSDFULibrary/Classes/Implementation/DFUServiceInitiator.swift#L270-L274

**Comment by longhunpeter** [comment]
my Podfile:
`platform :ios, '8.0'
target 'asthma' do
    use_frameworks!
    pod 'iOSDFULibrary'
end`
The version obtained is 4.2.1.
change podfile:
`platform :ios, '8.0'
target 'asthma' do
    use_frameworks!
    pod 'iOSDFULibrary','4.6.1'
end`
pod install 
error:
[!] CocoaPods could not find compatible versions for pod "iOSDFULibrary":
  In Podfile:
    iOSDFULibrary (= 4.6.1)

None of your spec sources contain a spec satisfying the dependency: `iOSDFULibrary (= 4.6.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by philips77** [comment]
You need to update CocoaPods: https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods
The new version requires `pod` in version 1.8 or something like this.
Older versions of `pod` do not support newer features and can obtain only some older version of the library.

**Comment by longhunpeter** [comment]
I upgraded the pod and got 4.6.1, but using "@import iOSDFULibrary;" prompted me "Module 'iOSDFULibrary' not found".

**Comment by philips77** [comment]
Did you do `pod update`?
Did you open the *xcworkspace*, not *xcodeproj* file?
Use:
```objective-c
#import <iOSDFULibrary-Swift.h>
```
Have a look at: https://medium.com/@anum.amin/swift-pod-library-in-objective-c-project-c6d1c5af997d

**Comment by philips77** [comment]
If you're using Swift, use:
```swift
import iOSDFULibrary
```

**Comment by longhunpeter** [comment]
I use oc.
I opened xcworkspace, using 4.2.1 is OK.
This link cannot be opened.
I look for other reasons.
thank you for your help.

**Comment by philips77** [comment]
We changed the zip dependency to ZipFramework some time ago. Check on that.

**Comment by longhunpeter** [comment]
I can now get 4.6.1.
Now there is another problem.
I have the following error when calling `[initiator startWithTarget: per]`:
![error](https://user-images.githubusercontent.com/5038649/75951053-e6beb100-5ee5-11ea-8207-0548bf0c8402.jpg)
This is my code:


        DFUServiceInitiator *initiator = [[DFUServiceInitiator alloc] withFirmware:selectedFirmware];
        initiator.delegate = self; // - to be informed about current state and errors
        initiator.progressDelegate = self; // - to show progress bar
        controller = [initiator startWithTarget:per];

**Comment by longhunpeter** [comment]
Is there a demo used by oc?

**Comment by longhunpeter** [comment]
I found the cause, it was a problem with my own project build settings.
Thank you for your patience.

**Comment by philips77** [comment]
Did you solve your issue?
