### ISSUE TITLE
typo in SecureDFUControlPoint.swift

### ISSUE THREAD

**Issue by jakerockland** [nordicsemi/IOS-DFU-Library#37]
There's a minor typo with the .invalidObject member of the SecureDFUResultCode enumeration, fixed this on our branch if you want to compare or pull the changes into the main repo: https://github.com/SomaticLabs/IOS-Pods-DFU-Library/pull/1

Also happy to make a PR if you let me know which branch to make it to @mostafaberg, not sure if you want to create a new bugfix branch.

**Comment by mostafaberg** [comment]
Fixed and will be included in the next update (2.1.5)
