### ISSUE TITLE
4.7.1 carthage issue has no shared framework schemes

### ISSUE THREAD

**Issue by AlexDM0** [nordicsemi/IOS-DFU-Library#370]
When installing the 4.7.1 version from Carthage (V0.34.0) 
```
github "NordicSemiconductor/IOS-Pods-DFU-Library" == 4.7.1
```
I get the following error:
*** Skipped building IOS-Pods-DFU-Library due to the error:
Dependency "IOS-Pods-DFU-Library" has no shared framework schemes

I can't really find any reason why it shouldn't work by looking at the releases and their contents... Maybe you guys have a suggestion?

**Comment by marcusgbrown** [comment]
We are seeing the same issue

**Comment by philips77** [comment]
I'll look into this.

**Comment by philips77** [comment]
https://github.com/Carthage/Carthage/pull/2965

**Comment by philips77** [comment]
Did you try previous version of dfu library, or older Carthage version?

**Comment by AlexDM0** [comment]
I have used 4.2.2 for a long time with Carthage. That worked fine. I figured I might upgrade now that it’s more than a year old.

________________________________

**Comment by philips77** [comment]
Hi, did you manage to solve the issue?
I'm about to release a new version and want to know how to fix Carthage configuration.

**Comment by philips77** [comment]
Ok, I manager to reproduce it as well. Will work on it now.

**Comment by AlexDM0** [comment]
I went back to 4.2.2 for now. Honestly had a lot of other work to do so I figured to postpone the update for now. I'll give 4.7.2 a try for our next release!

**Comment by philips77** [comment]
Sure! But remember, that 4.7.2 is so much better than 4.2.2. It's better by 0.5.0 ;)

**Comment by philips77** [comment]
Also, we switched from Zip to ZipFramework dependency at some point. Just FYI.

**Comment by AlexDM0** [comment]
I can't wait to see the massive boost of the 0.5 performance! Thanks for the help!
