### ISSUE TITLE
Xcode / Swift Package Manager instead of Cocoa Pods ?

### ISSUE THREAD

**Issue by smenor** [nordicsemi/IOS-DFU-Library#392]
**Your question**
It'd be incredibly useful / preferable to have this pulled out into a Swift Package rather than stored in Cocoa Pods / similar

These are built right into Xcode and don't require any weird monkeying with projects / workspaces and can be auto-updated from a Github repository with a click

https://developer.apple.com/documentation/swift_packages

**Comment by philips77** [comment]
We do support SPM. It's started on Readme file.

**Comment by smenor** [comment]
Oh that's awesome / thanks !

Much appreciated and best,
~ S
