### ISSUE TITLE
Crash when unwrapping optional after disconnection

### ISSUE THREAD

**Issue by nrbrook** [nordicsemi/IOS-DFU-Library#394]
In `SecureDFUExecutor.swift` `peripheralDidCreateDataObject()` the library performs an `asyncAfter`. When the block runs, down the stack it reaches `SecureDFUPeripheral.swift` `sendNextObject()`. This unwraps `dfuService`. If a disconnection occurs before the `asyncAfter` block is run, this will crash.

I exhibited it the first time I tried on macOS 10.15.7 (19H15), but have not seen it on iOS. Perhaps I just got lucky with my timing.

**Comment by philips77** [comment]
Let's say it's fixed. Will be released in 4.10.
