### ISSUE TITLE
alternativeAdvertisingName documentation does not specify maximum length

### ISSUE THREAD

**Issue by nrbrook** [nordicsemi/IOS-DFU-Library#395]
By examining the bootloader code I've found the maximum length is 20 bytes, but the DFU library documentation does not provide this information and the error logs that occur are misleading.

The errors are:

```
nRFDFU: Error 13: The value's length is invalid.
nRFDFU: Disconnected
nRFDFU: Buttonless service not configured, see: https://devzone.nordicsemi.com/f/nordic-q-a/59881/advertising-rename-feature-not-working/243566#243566. To workaround, disable alternative advertising name.
DFU error occurred (305): Writing to characteristic failed
```

While it does indicate the error code received was regarding the value's length, the following errors indicate there is a different problem.

**Comment by philips77** [comment]
Thank you for reporting this issue. I'll fix it in the next release.
