### ISSUE TITLE
Error while creating ZIP stream: The operation couldn’t be completed. (iOSDFULibrary.DFUStreamZipError error 0.)

### ISSUE THREAD

**Issue by mikkomanoza** [nordicsemi/IOS-DFU-Library#399]
Hi, i am new to this library. I follow and read the documentation, but i'm stuck because of this error -
"Error while creating ZIP stream: The operation couldn’t be completed.(iOSDFULibrary.DFUStreamZipError error 0.)"
how do I fix it? Thanks.

my code 
```swift
    import iOSDFULibrary

    var heartRatePeripheral: CBPeripheral!
    var dfuController: DFUServiceController!

    private func startUpdate(localFilePathURLStr: String) {

        let fileUrl = URL(fileURLWithPath: localFilePathURLStr)
        let selectedFirmware = DFUFirmware(urlToZipFile: fileUrl)
        guard let firmware = selectedFirmware else { return }

        let initiator = DFUServiceInitiator(queue: nil).with(firmware: firmware)

        initiator.logger = self
        initiator.delegate = self
        initiator.progressDelegate = self
        initiator.enableUnsafeExperimentalButtonlessServiceInSecureDfu = true;
        dfuController = initiator.start(target: heartRatePeripheral)
    }
```

**Comment by philips77** [comment]
Did you create your ZIP using [nrf util](https://github.com/NordicSemiconductor/pc-nrfutil)?

**Comment by mikkomanoza** [comment]
I did not create the zip file itself. how do I know if the zip file was created in nrf util? thanks @philips77

**Comment by philips77** [comment]
Check if you have the manifest.json file inside and 2 or 4 files with names equal as in the manifest.

**Comment by mikkomanoza** [comment]
the zip file I have is this (screenshot 1), but when I unzip the firmware.zip it contains manifest.json (screenshot 2), is firmware.zip the right one to use?, thank you for the quick answer @philips77 

screenshot 1: https://ibb.co/xj5ckNp
screenshot 2: https://ibb.co/19ttbcq

**Comment by philips77** [comment]
This is the error you're getting:
https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/d4a1da27fbf195b325cea3036235a4939a8f4efa/iOSDFULibrary/Classes/Utilities/Streams/DFUStreamZip.swift#L34-L52
Try printing the localized error message and see exactly what is the reason. Your zip file looks ok. You may also use the above mentioned nrfutil to read the content. Or debug where exactly you are getting that error from, which line.

**Comment by AbdElrahman-Rafaat-Amer** [comment]
Hi @philips77,  I have the same error. This is the localized error message: "The operation couldn’t be completed. (ZIPFoundation.Archive.ArchiveError error 0.)"

Do you have any solution?

**Comment by philips77** [comment]
Hi, is your device based on nRF5 SDK, or nRF Connect SDK? In the latter case you should use nRF Connect Device Manager library instead.
