### ISSUE TITLE
Update Readme to reflect support of SDK 12's SecureDFU

### ISSUE THREAD

**Issue by mrtzcspr** [nordicsemi/IOS-DFU-Library#40]
Looking casually at the project's readme-file one might assume that the latest supported SDK version is 8.

see: https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library#dfu-history

**Comment by mostafaberg** [comment]
Thanks a lot for the tip, will update soon !

**Comment by mostafaberg** [comment]
issue is now fixed
