### ISSUE TITLE
Compatibility with watchOS or tvOS?

### ISSUE THREAD

**Issue by evgzor** [nordicsemi/IOS-DFU-Library#408]
Why podspec not compatible with apple watchOS or tvOS. Is it any issue to use DFU library on those platforms?

**Comment by philips77** [comment]
No, we just didn't do any tests there. Please, prepare a PR with required changes and we'll merge it and release in the next version.

**Comment by evgzor** [comment]
I am testing now on aw current lib and when all test would be finished can provide changed podspec and readme files in this case

**Comment by philips77** [comment]
Please, create a PR to *develop* branch.

**Comment by philips77** [comment]
Merged.
