### ISSUE TITLE
Cannot abort DFU controller

### ISSUE THREAD

**Issue by jakerockland** [nordicsemi/IOS-DFU-Library#42]
When trying to abort my DFU controller like this, I'm getting a runtime error:

```
 var controller: DFUServiceController!
 let selectedFirmware = DFUFirmware(urlToZipFile:firmwareURL)
 let initiator = DFUServiceInitiator(centralManager: self.central, target: self.peripheral).withFirmwareFile(selectedFirmware!)

initiator.logger = self
initiator.delegate = self
initiator.progressDelegate = self

self.controller = initiator.start()

_ = self.controller.abort()
```

![screenshot 2016-10-25 14 42 32](https://cloud.githubusercontent.com/assets/8602661/19705435/5c8dcf7a-9ac1-11e6-9fe2-83889c97ee37.png)

**Comment by jakerockland** [comment]
@mostafaberg Could I get your thoughts on this?

**Comment by mostafaberg** [comment]
if you try to abort the controller before it starts it has not discovered at that moment yet if it's a Secure or Legacy DFU so there's nothing to abort per se, however we should handle this more gracefully

does this happen during the even if you abort in the middle of the DFU operation ?

**Comment by jakerockland** [comment]
Hmm, that makes sense @mostafaberg, I haven't had this issue when trying to abort mid-DFU but have tried to use the .abort() function when hanging in the "disconnecting" state as noted in #43, which is where I noticed this behaviour.

**Comment by mostafaberg** [comment]
True, i can confirm this happens, i'll try to get that resolved as soon as I can, will have much more time soon assigned to fixing all those bugs ! thanks for your patience

**Comment by jakerockland** [comment]
Not a problem, thank you @mostafaberg ! 👍

**Comment by philips77** [comment]
Hi, the Version 3 is now published on our Version3 branch. You can edit your Profile and give the whole repo and branch path there. This bug has been fixed in this version, I hope :)
Version 3 is now in beta phase and we will publish it when we get some feedback.
Thanks!

**Comment by jakerockland** [comment]
Version 3 seems to be working for us! Going to close this issue for now. 😄
