### ISSUE TITLE
error: could not find module 'iOSDFULibrary' for target 'arm64-apple-ios-simulator'

### ISSUE THREAD

**Issue by kelvin-lima** [nordicsemi/IOS-DFU-Library#422]
**Information**

When am I archiving my framework, that uses iOSDFULibrary, I have faced this issue. There's any reason to not make available IOSDFULibrary for Arm64-Simulator?

**DFU Bootloader version (please complete the following information):**
 - Library version: 4.10.2

**Device information (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.5

** LOGS ** 

error: could not find module 'iOSDFULibrary' for target 'arm64-apple-ios-simulator'; found: i386, x86_64-apple-ios-simulator, x86_64, i386-apple-ios-simulator

**Comment by mnich0ls** [comment]
Thanks @kelvin-lima
