### ISSUE TITLE
Module compiled with Swift 5.3.2 cannot be imported by the Swift 5.4 compiler

### ISSUE THREAD

**Issue by IIkhsan** [nordicsemi/IOS-DFU-Library#425]
**DFU Bootloader version (please complete the following information):**
 - Library version: 4.10.3

**Device information (please complete the following information):**
- Xcode 12.5
- Xcode command tools 12.5

**Your question**
Module compiled with Swift 5.3.2 cannot be imported by the Swift 5.4 compiler

**Logs**
![Снимок экрана 2021-05-14 в 11 04 54](https://user-images.githubusercontent.com/22461592/118240936-39113f80-b4a4-11eb-8641-60b69a2ec02e.png)

**Comment by philips77** [comment]
What package manager are you using? Please rebuild the library to Swift version of your choice.

**Comment by philips77** [comment]
Closing the issue due to inactivity.
