### ISSUE TITLE
Pod not building on Xcode 13 Beta & iOS 15 Beta

### ISSUE THREAD

**Issue by juliansteenbakker** [nordicsemi/IOS-DFU-Library#428]
**Information**
I tried building this pod for a flutter plugin with the Xcode 13 Beta, however it gives a lot of errors. Seems to be something with unwrapping the service from the characteristic object. See the logs for more information.

**DFU Bootloader version:**
 - Library version: 4.10.3

**Device information:**
 - Device: iPad Air 2
 - OS: iOS 15 Beta

**Logs**
(Image because full stack trace is too long for Github)
![image](https://user-images.githubusercontent.com/20091319/121519060-8a541680-c9f1-11eb-8a00-984a82771f28.png)

**Comment by philips77** [comment]
Thank you for creating the issue. I really like Apple for caring about backwards compatibility.

**Comment by evnik** [comment]
This seems to be because of this kind of [API changes](https://developer.apple.com/documentation/corebluetooth/cbservice/1434334-peripheral?changes=latest_minor)

**Comment by juliansteenbakker** [comment]
> This seems to be because of this kind of [API changes](https://developer.apple.com/documentation/corebluetooth/cbservice/1434334-peripheral?changes=latest_minor)


At least its not like Android where everything gets deprecated after a new api release.. 😅

**Comment by dinesharjani** [comment]
Fixed: https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/pull/433
