### ISSUE TITLE
How is IOS-Pods-DFU-Library different than IOS-DFU-Library?

### ISSUE THREAD

**Issue by lilliesAndRoses** [nordicsemi/IOS-DFU-Library#5]
Hello,
I see there are two DFU library repositories here. Do they differ simply in the packaging or is there any other difference? Also, do the updates in one repository get added to the other as well? 

Which one is recommended?

Thanks.

**Comment by mostafaberg** [comment]
Hi @lilliesAndRoses , they are the same, updates are published at the same time so they are always on the same revision so it's just a different way of packaging as you guessed.

We recommend using Cocoapods as it's easier to integrate into projects and makes it very easy to release and handle updates / dependencies.
