### ISSUE TITLE
Error when Dfu_v1 firmware is greater than 0xFFFF bytes

### ISSUE THREAD

**Issue by sschiffli** [nordicsemi/IOS-DFU-Library#54]
Copy from https://github.com/NordicSemiconductor/IOS-DFU-Library/issues/25

The exact error we are seeing is "Error: 65760 bytes were sent while 224 bytes were reported as received"

The issues stems from the fact that older bootloader versions represented the received firmware image size as a uint16_t (thus we saturate) and sometime later it changed to uint32_t. This library always interprets the field as a uint32_t. https://github.com/NordicSemiconductor/IOS-DFU-Library/blob/master/DFULibrary/DFUControlPoint.swift#L196

Since we still have old devices in the field to support I've had to modify [LegacyDFUService.swift](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/LegacyDFU/Services/LegacyDFUService.swift#L333) from
`if bytesSent == bytesReceived {`
to
`if bytesSent == bytesReceived || bytesSent == (bytesReceived + 0x10000) {`

**Comment by philips77** [comment]
Hi, could you try Version3 branch? 
You can change the Podfile as in nRF Toolbox app.

**Comment by philips77** [comment]
Ok, I think I have seen this issue on Android Dfu lib. I'll take a look tomorrow. The fix will go to the version3 branch.

**Comment by philips77** [comment]
We also accept pull requests :)

**Comment by sschiffli** [comment]
Still present on Version3, I'll submit my workaround in a pull request

**Comment by mostafaberg** [comment]
Thanks a lot for the PR ! we will look into it and Merge as soon as possible :)

**Comment by philips77** [comment]
Hi @sschiffli,
Could you try now with the Version3 branch? If you are using Pods, and configured it to use the Version3 branch, just type ```pods update``` in console and the new commits should be obtained. I did some tests but could you verify it works in your project?
Thanks again for reporting the issue!

**Comment by sschiffli** [comment]
Looks great, thanks!

**Comment by sschiffli** [comment]
eb83378 broke the case where the legacy DFU _did_ report bytes received as 32bits (sometime after the SDK 5.2.0.39364 release).
`if (bytesSent & 0xFFFF) == bytesReceived {`
Once bytes received goes over 0xFFFF this comparison will fail.  I think we should mask both bytesSent and bytesReceived.
`if (bytesSent & 0xFFFF) == (bytesReceived & 0xFFFF) {`

**Comment by philips77** [comment]
True. Good catch!

**Comment by philips77** [comment]
Done.

**Comment by sschiffli** [comment]
I also noticed some changes in DFUControlPoint.swift which aren't really necessary.  Even in the  SDK 5.2.0.39364 DFU code, the response over the wire was in fact 5 bytes long.  This means all the code in the [else block](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/eb83378fba47d1400d5912df01d3f18b9a887f55/iOSDFULibrary/Classes/Implementation/LegacyDFU/Characteristics/DFUControlPoint.swift#L196) in unreachable.

**Comment by philips77** [comment]
I was wondering why the app didn't crash before the bytesSent and bytesReceived comparison in your case... But I think we can leave it like that, hym?

**Comment by sschiffli** [comment]
Whatever you think will be less confusing down the line from a maintenance perspective.  I just doubled checked to confirm that it is in fact dead code.

**Comment by philips77** [comment]
Thanks again for testing it.

**Comment by philips77** [comment]
Hi, after all I decided to remove the dead code and just add some information about the issue.
I pushed the https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/commit/0e2983c6252d9047cb4c4a0d29bcd3002f1031f0 to Version3 branch.

**Comment by StrawHatAaron** [comment]
I am facing this issue with the cocoa pods version 'iOSDFULibrary', '~> 4.0'

except I get Error: 1080 bytes were sent while 40 bytes were reported as received"
