### ISSUE TITLE
forceDfu parameter not copied in DFUExecutor

### ISSUE THREAD

**Issue by sschiffli** [nordicsemi/IOS-DFU-Library#55]
The generic executor doesn't copy the the forceDfu parameter from the original initiator.

I think that in both [startSecureDFU](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/GenericDFU/DFUExecutor.swift#L67) and [startLegacyDFU](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/GenericDFU/DFUExecutor.swift#L81) then should also have:
`dfuInitiator.forceDfu = initiator.forceDfu`

**Comment by philips77** [comment]
Could you try the Version3 branch? This version is currently almost ready to replace the current master one.

**Comment by sschiffli** [comment]
Issue solved on Version3, Thanks!
