### ISSUE TITLE
Generate IPA file

### ISSUE THREAD

**Issue by hiniesta** [nordicsemi/IOS-DFU-Library#7]
When I add the DFULibrary, I can't archive my target to a IPA file. In Organizer appears as Other Items, but cannot export as IPA file. Any help? Thanks

**Comment by mostafaberg** [comment]
That's probably cause you're building the wrong target, make sure you're selecting your app's target and not the cocoapods' target and things should be fine, if you have further questions please remember to post them on our developer center so you can get further help with your issue
