### ISSUE TITLE
upload appstore failed,  contains disallowed file 

### ISSUE THREAD

**Issue by ziyouzhe4** [nordicsemi/IOS-DFU-Library#70]
hi  , When I uploaded to AppStore failed, show the following information,
 
![snip20161222_1](https://cloud.githubusercontent.com/assets/8589860/21448074/2fa9a714-c919-11e6-9335-91bc2a512df7.png)

i use the latest Xcode version  and i  do fllow this   http://stackoverflow.com/questions/30547283/submit-to-app-store-issues

it's show me that

![snip20161223_2](https://cloud.githubusercontent.com/assets/8589860/21448684/3d06f0c2-c920-11e6-9eda-4bc6da410183.png)

**Comment by JJCoderiOS** [comment]
i read this art is not  success   http://stackoverflow.com/questions/30547283/submit-to-app-store-issues

**Comment by mostafaberg** [comment]
Could be an issue with Cocoapods or your project configuration.
-Which version of cocoapods are you using ?
-How are you building the project ?

**Comment by ziyouzhe4** [comment]
hi,i have solved the problem ,i run  script :

cd "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/"
if [[ -d "Frameworks" ]]; then
rm -fr Frameworks
fi

in build phases 

however, the ZIP and iOSDFULibrary  framework  make the ipa huge....

**Comment by mostafaberg** [comment]
This is a workaround not a fix, can you please answer my questions ?

**Comment by ziyouzhe4** [comment]
cocoapods version   1.1.0.beta.2
how to buildiong the project ?  what's your means?

**Comment by mostafaberg** [comment]
Prefect, when i mean building i mean what are the steps that you do in Xcode to get the IPA file ?

**Comment by ziyouzhe4** [comment]
aha~~~~  Product - > archive ~~~

**Comment by mostafaberg** [comment]
That sounds about right, could it be something with your build settings ? what are you `valid architectures` values set to ? are you targetting MacOS ? or just iOS ?

**Comment by mostafaberg** [comment]
@JJCoderiOS Any news ? did you get your issue resolved ? This issue will be closed in 24 hours if we got no response and we will assume you fixed it
