### ISSUE TITLE
DFUController.restart() method has been removed – how can I restart the DFU process?

### ISSUE THREAD

**Issue by larsblumberg** [nordicsemi/IOS-DFU-Library#71]
In earlier versions of this library (at least 1.x) there was a method `restart()` for protocol `DFUController`. It was very useful, because very often the first firmware update fails with error code `DFUError.deviceDisconnected`. In earlier versions if would simply do:

```
public func dfuError(_ error: DFUError, didOccurWithMessage message: String) {
    if error == .deviceDisconnected {
        // For some reason Nuimo/DFU library disconnects very often during first connection attempt, simply restart DFU
        dfuController.abort()
        // Following method has been removed :´(
        dfuController.restart()
        return
    }
    ...
}
```

Aborted firmware updates are a very bad user experience and prior to version to 3.x we could avoid that in all cases at the update at least always worked in the 2nd attempt. The user wouldn't even have noticed the abortion of the first attempt.

What do you suggest ist the best way to recover from a `DFUError.deviceDisconnected` during a firmware update?

(This issue might be related to #62)

**Comment by mostafaberg** [comment]
for Secure DFU there's nothing special to be done, simply starting the DFU process again will automatically resume from the last point

**Comment by larsblumberg** [comment]
What about non-secure updates? We're using an older Nordic SDK and thus can't provide secure updates yet. This said, "legacy updates" are performed.

Can we still restart? If yes, how?

**Comment by philips77** [comment]
In legacy DFU the device should be automatically resetted when DFU fails or is aborted. No need to do anything.

**Comment by philips77** [comment]
There is actually more problems with Secure DFU, as the current impl (SDK 12.x) does not support resetting back to app mode, as far as i know.

**Comment by larsblumberg** [comment]
Why shouldn't we do anything? What about the user not getting his firmware update?

**Comment by philips77** [comment]
What do you mean by " user not getting his firmware update"? Could you elaborate?

Whenever an error occurs, the resetDevice() method is called: https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/GenericDFU/DFUExecutor.swift#L113 
For Legacy DFU it does this: https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/LegacyDFU/Peripherals/LegacyDFUPeripheral.swift#L177

**Comment by larsblumberg** [comment]
If the firmware update has failed, the user's device will still carry the old firmware version.

How can we provide an automatic update retry mechanism from the app side? In older versions of this library we would simply call `restart()` – please see my original question at the top.

**Comment by philips77** [comment]
Ok, I get it now! :) Sorry!

**Comment by philips77** [comment]
I'll have a look at the code and try to add it back. Sorry for that. Never thought someone was using it actually :)

**Comment by larsblumberg** [comment]
It turns out, a firmware update retry can be implemented as following. I argue that your library should provide this method again as it was already part of older versions. I want to stress again that it is a bad user experience if something fails and we don't retry, especially in this case where it solves the issue as easy that.

```
let dfuInitiator = DFUServiceInitiator(...)
...
var dfuController = dfuInitiator.start()
...
public func dfuError(_ error: DFUError, didOccurWithMessage message: String) {
    if error == .deviceDisconnected {
        dfuController.abort()
        dfuController = dfuInitiator.start()
    }
}
```

Again, it would be great if I could simply call `dfuController.restart()` instead of the workaround above.

Anyway, with that workaround we can again provide a better user experience. Failed firmware updates happen very often on iOS and macOS. I guess there's some bug in this library.

**Comment by philips77** [comment]
> Failed firmware updates happen very often on iOS and macOS. I guess there's some bug in this library?

I actually find the lib very stable, I have to say, but we are using just the simple HRM apps for testing. I will look into the ```restart()``` and retry problem.
Could you tell when do you get most errors? And what kind of errors?

**Comment by larsblumberg** [comment]
The lib _is_ stable, except the fact that firmware updates nearly never work on the first try. As already mentioned above `DFUError.deviceDisconnected` is being sent from the library via `DFUServiceDelegate` when doing legacy updates.

**Comment by larsblumberg** [comment]
Do you test with the older Nordic SDK version 8.0, too?

**Comment by philips77** [comment]
Yes, we do. I'll come back to you tomorrow.

**Comment by philips77** [comment]
Hi, I've added the restart() method in Version3 branch (https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/tree/Version3). Could you give it a try before I push to Pods?

> Modify the Podfile like here: https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/blob/master/Podfile#L3

**Comment by philips77** [comment]
Hi @larsblumberg , did you test the new/old method and the latest changes on Version3 branch? Should we release it on Pods?

**Comment by larsblumberg** [comment]
Sorry for my late reply. I didn't yet test the branch since I'm using the workaround I mentioned above.

But if you push a new DFU library version I will check.

**Comment by philips77** [comment]
Hi, the version 3.0.4 is now available on Pods. I'm closing this issue. Please reopen it if you find this feature not working as expected.
