### ISSUE TITLE
Crash in DFUPeripheral line 161

### ISSUE THREAD

**Issue by larsblumberg** [nordicsemi/IOS-DFU-Library#72]
It just crashed for me here:

https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary/Classes/Implementation/GenericDFU/DFUPeripheral.swift#L161

```
    func abort() -> Bool {
        aborted = true
        if peripheral?.state == .connecting { // <<<<<------- CRASH
            disconnect()
        }
        return true
    }
```

Reason is because you're force-unwrapping an optional object. I've seen this in a few places in the library. It should be generally avoided.

**Comment by philips77** [comment]
I'm forcing unwrapping when the variable needs to be set so the crash is as fast as possible. 
But here it definitely should be ? as peripheral may legally be nil when you scan for new one. Will change it right away.

**Comment by larsblumberg** [comment]
Thanks a lot for fixing it so quickly.

**Comment by philips77** [comment]
I pushed some commits. One fixes this issue, another just replace ifs with guards. Hope it still works.
