### ISSUE TITLE
Can't find spec for 'Zip' module

### ISSUE THREAD

**Issue by kevinpk** [nordicsemi/IOS-DFU-Library#75]
I'm trying to install the DFU pod in my project but get this error when running pod install:
`[!] Unable to find a specification for 'Zip (~> 0.6)' depended upon by 'iOSDFULibrary'`

Here is my Podfile:
`target 'DFU_test' do`
`  use_frameworks!`
`  pod 'iOSDFULibrary'`
`  # Pods for DFU_test`
`end`

Using Cocoapods version 1.1.1 and Xcode 8.2

**Comment by mostafaberg** [comment]
You probably need to update your cocoapods repo, try this:
`pod repo update`
and then you may run
`pod install`

let me know how it goes

**Comment by kevinpk** [comment]
Thanks for the suggestion @mostafaberg. I ended up having to delete, then recreate my specs repo:

`pod repo remove master`
`pod setup`

Then `pod install` finally worked!
