### ISSUE TITLE
Use of undefined identifier 'DFUStateSignatureMismatch' in Objective C

### ISSUE THREAD

**Issue by nhatminh12369** [nordicsemi/IOS-DFU-Library#88]
My project is written in Objective C and I am trying to use this library. However, this is the error that I am getting:
`Use of undefined identifier 'DFUStateSignatureMismatch'`

I have tried to install this library into my project using Cocoapod, Carthage and also copy the code directly into my project but I am still getting that error. Please help!

**Comment by mostafaberg** [comment]
We do not have any enum named DFUStateSignatureMismatch in the library, you probably updated the iOSDFULibrary with a breaking changes version and didn't update your code to follow those changes, can you show us some code snippet where this is triggered ?

**Comment by mostafaberg** [comment]
@nhatminh12369 Did you manage to resolve your issue ?

**Comment by nhatminh12369** [comment]
I have resolved the issue above. I was because I upgraded the library to the latest version and didn't notice that this enum is no longer exists: DFUStateSignatureMismatch.
Thanks @mostafaberg.
