### ISSUE TITLE
When killing the app during a dfu upload, the upload gives an invalid state error

### ISSUE THREAD

**Issue by matthewchung74** [nordicsemi/IOS-DFU-Library#9]
I am getting an error where I start doing a DFU upload of an application firmware, then kill the toolbox app, and then try to upload the firmware again. I always get an invalid state error.

Is it possible I need to send an `abort` to the DFUPeripheral before sending a `start`?

**Comment by philips77** [comment]
I think it's related to https://github.com/NordicSemiconductor/nRF-Master-Control-Panel/issues/16

**Comment by matthewchung74** [comment]
hi @philips77 i didn't realize that repo above was only for android. do you know when there might be a fix on iOS i can test with?

**Comment by philips77** [comment]
Hi, I guess some time early next week, but we'll see. @mostafaberg

**Comment by mostafaberg** [comment]
I'm on it, I'll check if I can do a good fix on Monday !, can't promise a lot as it's not a very high priority issue but we will see next week 👍

**Comment by mostafaberg** [comment]
Ok i took a look and already started working on a fix, will have something out during this week!

**Comment by matthewchung74** [comment]
Thank you so much @mostafaberg

**Comment by mostafaberg** [comment]
No worries!,
I've just resolved the issue now and in the process of publishing the new Pod and it will be available soon, the version number you're looking for is 0.1.9 build 9, let me know if you have any other issues!

**Comment by matthewchung74** [comment]
@mostafaberg since the pod repo has not updated yet, can you create a tag on github so i can just reference the tag for testing purposes?

**Comment by mostafaberg** [comment]
It's already tagged 0.1.9, you can check it out here:
https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/releases/tag/0.1.9

**Comment by matthewchung74** [comment]
Testing now, seems great.

**Comment by mostafaberg** [comment]
Great news !, thanks for the feedback
