### ISSUE TITLE
dfuStateDidChangeTo: unrecognized selector sent

### ISSUE THREAD

**Issue by aahirgiri** [nordicsemi/IOS-DFU-Library#90]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ViewController dfuStateDidChangeTo:]: unrecognized selector sent to instance 0x155e08870'
***
 First throw call stack:
(0x18f8851b8 0x18e2bc55c 0x18f88c268 0x18f889270 0x18f78280c 0x10023f544 0x10022f0d4 0x100bc5258 0x100bc5218 0x100bca280 0x18f832810 0x18f8303fc 0x18f75e2b8 0x191212198 0x1957a57fc 0x1957a0534 0x1000bfb10 0x18e7415b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

I'm calling [initiator start] after assigning zip file and also verified that the selected peripheral and selected firmware have correct values. But I'm unable to figure out why this is happening.

**Comment by mostafaberg** [comment]
Probably you're not setting the view controller as the delegate, you may use [this as a reference](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/Example/iOSDFULibrary/DFUViewController.swift#L27)

**Comment by aahirgiri** [comment]
I have set the view controller as the delegate. No luck still

**Comment by mostafaberg** [comment]
I'm not sure it's hard to tell the issue without seeing the source code, but i would recommend just trying to uninstall the library by doing a `pod deintegrate`, then running `pod update` and try again.

**Comment by mostafaberg** [comment]
@aahirgiri Any luck with this yet ?

**Comment by aahirgiri** [comment]
No luck. I'm still trying :(

**Comment by mostafaberg** [comment]
If you can share the project that causes the issue or the github repo we might be able to take a look and send back a fix

**Comment by aahirgiri** [comment]
Thanks. You can find the project here:

https://github.com/aahirgiri/TestProj_DFU.git

**Comment by aahirgiri** [comment]
Please pull the latest changes. I have modified the UUID again

**Comment by mostafaberg** [comment]
will do 👍

**Comment by mostafaberg** [comment]
@aahirgiri Sent you a PR that will hopefully get this working, you forgot to implement the actual delegate methods but defined them in the view's header, I've added some `HACK` warnings in the `.m` file so you just check your warnings and you'll see what needs to be implemented

**Comment by mostafaberg** [comment]
@aahirgiri Also remember to only start scanning AFTER the CentralManager's state is ready, before that you should disable the scan button or something since it'll confuse the user when they press scan and nothing happens.

**Comment by aahirgiri** [comment]
Works! Thanks a ton :)
