### ISSUE TITLE
Invalid Argument Exception

### ISSUE THREAD

**Issue by coding-watermelon** [nordicsemi/IOS-DFU-Library#92]
Hello,

I integrated your library into my project in order to implement the DFU upgrade. 

But as it comes to start the upgrade, I get a `NSInvalidArgumentException', reason: '-[BleManager dfuStateDidChangeTo:]: unrecognized selector sent to instance 0x1740d7840'`.

It occurs within the async part in following code from ```DFUServiceSelector```

```
func start() {
        DispatchQueue.main.async(execute: {
           self.delegate?.dfuStateDidChange(to: .connecting)
        })
        peripheral.start()
    }
```

That is the code I am calling it from. Did I do anything wrong? I checked the peripheral and it looked fine.

<img width="1388" alt="bildschirmfoto 2017-02-19 um 22 53 21" src="https://cloud.githubusercontent.com/assets/5831420/23107150/34c9b77c-f6f8-11e6-9951-72c09fdb82c7.png">

Thanks!

**Comment by mostafaberg** [comment]
Hi @PetrykowskiM !, I see the address in the error message `0x1740d7840` is pointing to a `CBCentralManager` object in the screenshot. `CBCentralManager` doesn't implement the delegate methods for the DFU service controller, which class is that code running in ? `BleManager` I would assume ? if so try setting that as the delegate, and make sure it implements the correct delegate methods like `dfuStateDidChangeTo`, etc ...

**Comment by coding-watermelon** [comment]
Thank you, this solved my problem :) Kind of tricky to implement your swift classes with objective c. Maybe you would want to add some documentation for it?

**Comment by mostafaberg** [comment]
Glad it worked out, we actually don't support Objective-C that's why there's no documentation for it, Swift 3 is our main focus right now
