### ISSUE TITLE
dyld: Library not loaded: @rpath/Zip.framework/Zip

### ISSUE THREAD

**Issue by pjl1234567** [nordicsemi/IOS-DFU-Library#93]
My Enviorments:
macOS 10.12.2
Xcode 8.2
Library
github "NordicSemiconductor/IOS-Pods-DFU-Library" ~> 3.0.6
github "marmelroy/Zip" ~> 0.6

1.  I installed carthage
2. Create a file named cartfile on my computer
3. add the following content to the file:

```
github "NordicSemiconductor/IOS-Pods-DFU-Library" ~> 3.0.6
github "marmelroy/Zip" ~> 0.6
```

1. then I open a new terminal and cd to the directory where the cartfile  file is
2. Enter the command carthage update --platform iOS
3. Last i drag the ```Carthage/Build/iOS/iOSDFULibrary.framework```  and    ```Carthage/Build/iOS/Zip.framework```  to my  project.

but when I run it , follow  the error：
![1](https://cloud.githubusercontent.com/assets/10611230/23454834/8a758eb4-fea8-11e6-9ffc-eecaeca10cb6.png)
@mostafaberg

**Comment by mostafaberg** [comment]
I think dragging will just add the files to the project and not link them, try adding them from the project configuration's `Link Binary With Libraries` tab if it's not already there

**Comment by pjl1234567** [comment]
```Link Binary With Libraries``` tab 
![22](https://cloud.githubusercontent.com/assets/10611230/23488827/ff28079c-ff29-11e6-8999-660059c8209e.png)

**Comment by pjl1234567** [comment]
[here](https://github.com/pjl1234567/MYDFUTest) is my test code

**Comment by pjl1234567** [comment]
@mostafaberg

**Comment by mostafaberg** [comment]
Thaks for posting code, will look into it now !

**Comment by mostafaberg** [comment]
The libraries aren't being embedded that's why the images can't be found.
You need to add the libraries to the `embedded binaries` tab, you also need to set `always embed swift standard binaries` to `Yes` in your build settings.

**Comment by pjl1234567** [comment]
Thanks for your help very much。 @mostafaberg
