### ISSUE TITLE
EXC_BAD_ACCESS on the Initiator .with(firmware: ) call.

### ISSUE THREAD

**Issue by kodartcha** [nordicsemi/IOS-DFU-Library#94]
Hello. I already commented on the only issue I could find related to this problem but I don't know if anyone will see it as it is already closed.

Today I updated the iOS DFU Library and I am getting the EXC_BAD_ACCESS (code=1, address=0x10). Before the update everything was working properly.

I also tried removing and reinstalling all the pods from scratch.

Here is my code:
```
func setFilePath(){
        let bundleURL = Bundle.main.bundleURL
        let dataFolderURL = bundleURL.appendingPathComponent("firmware")
        let fileURL = dataFolderURL.appendingPathComponent("edd_new.hex")
        
        let fileManager = FileManager.default
        if fileManager.fileExists(atPath: fileURL.path) {
            print("FILE AVAILABLE")
        } else {
            print("FILE NOT AVAILABLE")
        }
        
        let selectedFirmware = DFUFirmware(urlToBinOrHexFile: fileURL, urlToDatFile: nil, type: DFUFirmwareType.application)
        
        startUpdate(selectedFirmware!)
    }
    
    
    func startUpdate(_ fw: DFUFirmware){
        
        if(self.dfuPeripheral == nil){
            print("DFU PERIPHERAL NIL")
        }
        
        let initiator = DFUServiceInitiator(centralManager: centralManager!, target: self.dfuPeripheral!)

        initiator.logger = self; // - to get log info
        initiator.delegate = self; // - to be informed about current state and errors
        initiator.progressDelegate = self; // - to show progress bar
        
        self.dfuController = initiator.with(firmware: fw).start()
    }
```

File is available, and peripheral is not nil. It also crashes on the .with(firmware: fw) part. Tried both to put in on the initiator declaration and before the start as the code shows. Same problem. 

Is there any way I can fix this? Thank you!

**Comment by mostafaberg** [comment]
Hi ! can you breakpoint right after the line `let selectedFirmware` and print out the contents of `selectedFirmware` ?

**Comment by kodartcha** [comment]
Hi @mostafaberg , thanks for the fast reply. This is what you need?

![captura de pantalla 2017-03-09 a las 15 35 42](https://cloud.githubusercontent.com/assets/18568521/23754673/212bfeb6-04de-11e7-9390-b91d53acee9f.png)

**Comment by kodartcha** [comment]
Hi @mostafaberg. Any update on the issue? I would really appreciate your help as the APP is published with that bug and we need to update it as fast as possible. Our clients are not able to update their devices. Thanks a lot!

**Comment by kodartcha** [comment]
Hi. I was able to fix it by downgrading to pod version 2.0.1. The 3.0.0 also not working. At the moment we will release with this version, but a solution for the newer one would be much appreciated. Thanks.

**Comment by mostafaberg** [comment]
Sorry for the delayed response, I will look into it and update you within the week !, glad to hear you have a working version out for now!

**Comment by mostafaberg** [comment]
I have checked this over and over and I couldn't reproduce that issue, is it possible that you can make a simple project that reproduces this so i can experiment with it ?

**Comment by kodartcha** [comment]
Hi @mostafaberg. I am sorry but I am really busy those days with internal projects. But I promise as soon as I have some time I will do it and let you know. Thank you and BR.

**Comment by mostafaberg** [comment]
Ofcourse !, no worries, if i manage to reproduce this i'll let you know here the version that fixes that:) thanks and appreciate the feedback

**Comment by bisikli** [comment]
Hello, i think i have the same problem:

<img width="1280" alt="ekran resmi 2017-07-07 15 44 49" src="https://user-images.githubusercontent.com/16748312/27959439-17c78b6e-6330-11e7-97df-7f650d56d38a.png">

**Comment by bisikli** [comment]
Hello @mostafaberg, you had any chance to look into this issue? Thanks

**Comment by mostafaberg** [comment]
@bisikli This seems to be a different issue, you should open a separate issue so we can take it there :)
