### ISSUE TITLE
Is there any plane to port to React-Native lib in someday?

### ISSUE THREAD

**Issue by dubiao** [nordicsemi/IOS-DFU-Library#99]
I am about to create our next project base on React-Native tech. It's easy to get normal BLE functions to work but the DFU is a little difficult for me. I try port it by myself but get many more insolubility problems.

> I posted this issue on Android-DFU-Library repository also. see [here](https://github.com/NordicSemiconductor/Android-DFU-Library/issues/52).

**Comment by mostafaberg** [comment]
We do not have any plans for supporting React Native, however, I'm pretty sure you don't need to port it, you can still get the library to work and somehow bridge it to your JS code.
I'm not sure how that is exactly done though, but here's a starter in the right direction:
https://facebook.github.io/react-native/docs/native-modules-ios.html
